---
title: "Acidez Total Titulable y Sólidos Solubles"
output: pdf_document
---

``` {r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(readxl)

ATTSS <- read_excel("muestrasquimica.xlsx", sheet="Hoja7")

ATTSS$year<-factor(ATTSS$year,levels=c("2022"))

ATTSS$site<-factor(ATTSS$site,levels=c("concordia", "palmar","gualeguaychu"))

ATTSS$phenotype<-as.factor(ATTSS$phenotype)

ATTSS$id <-factor(ATTSS$id,levels=c("1", "2","3","4"))

ATTSS$mad <- as.factor(ATTSS$mad)

```

## Descriptive table for brix
```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(dplyr)

table_acidity <- ATTSS %>% 
  dplyr::group_by(site, phenotype) %>%
  dplyr::summarise(
    n = n(),
    Mean = mean(acidity),
    min = min(acidity),
    max = max(acidity),
    sd = sd(acidity),
    )

table_acidity
```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)

gATT<-ggplot(data=table_acidity, aes(x=phenotype, y=Mean, fill=site))+
  stat_summary(fun = "mean", size = 1, geom = "bar") +
  geom_errorbar(aes(ymin=Mean-sd, ymax=Mean+sd),
                width=.2, position=position_dodge(.9))+
  # facet_grid(.~year)+
  labs(x="", y="ATT (%)")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
  scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
  theme(legend.title=element_blank())+
  theme(legend.position='bottom')+
  theme(panel.grid.major.y = element_line(color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='black'))+
  theme(axis.text = element_text(color='black'))


```

## Descriptive table for SS.
```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(dplyr)

table_brix <- ATTSS %>% 
  dplyr::group_by(site) %>%
  dplyr::summarise(
    n = n(),
    Mean = mean(brix),
    min = min(brix),
    max = max(brix),
    sd = sd(brix),
    )

table_brix

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)

gATT_brix<-ggplot(data=table_brix, aes(x=site, y=Mean, fill=site))+
  stat_summary(fun = "mean", size = 1, geom = "bar") +
  geom_errorbar(aes(ymin=Mean-sd, ymax=Mean+sd),
                width=.2, position=position_dodge(.9))+
  # facet_grid(.~year)+
  labs(x="", y="°Brix")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
  # scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
  theme(legend.title=element_blank())+
  theme(legend.position='none')+
  theme(panel.grid.major.y = element_line(color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='black'))+
  theme(axis.text = element_text(color='black'))


```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)

gATT_brix_dispersion<-ggplot(data=ATTSS, aes(x=acidity, y=brix, fill=site, color=phenotype))+
  geom_point(size=5)+
  # facet_grid(.~year)+
  labs(x="ATT (%)", y="°Brix")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
  scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
  # scale_color_manual(values = c("coral1","burlywood2","palegreen4")) +
  theme(legend.title=element_blank())+
  theme(legend.position='bottom')+
  theme(panel.grid.major.y = element_line(color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='black'))+
  theme(axis.text = element_text(color='black'))


```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)

gATT_phi_dispersion<-ggplot(data=ATTSS, aes(x=pHi, y=brix, fill=site, color=site, shape=mad))+
  geom_point(size=5)+
  # facet_grid(.~year)+
  labs(x="pHi", y="Brix")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
  scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
  # scale_color_manual(values = c("coral1","burlywood2","palegreen4")) +
  theme(legend.title=element_blank())+
  theme(legend.position='bottom')+
  theme(panel.grid.major.y = element_line(color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='black'))+
  theme(axis.text = element_text(color='black'))


```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)

gATT_phi_dispersion<-ggplot(data=ATTSS, aes(x=pH81, y=acidity, fill=site, color=site, shape=mad))+
  geom_point(size=5)+
  # facet_grid(.~year)+
  labs(x="pH 8.1", y="ATT (%)")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
  scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
  # scale_color_manual(values = c("coral1","burlywood2","palegreen4")) +
  theme(legend.title=element_blank())+
  theme(legend.position='bottom')+
  theme(panel.grid.major.y = element_line(color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='black'))+
  theme(axis.text = element_text(color='black'))

```