---
title: "Bibliografía"
---

*	Aburto, N.J.; Hanson, S.; Gutierrez, H.; Hooper, L.; Elliott, P.; Cappuccio, F.P. 2013. Effect of increased potassium intake on cardiovascular risk factors and disease: Systematic review and meta-analyses. BMJ 346, f1378.
*	Agostini, J.P., Preussler, C., Outi, Y., Cortese, P.P., Bouvet, J. 2015. Plagas cuarentenarias de frutales de la República Argentina Avances en los resultados. Revista, 36: 1-36.
*	Agrimundo. 2013. Perspectivas para los berries nativos en el mercado internacional. Revista, 1: 1-1.
*	Ahmad, A.; Khalid, N. 2018. Chapter 5—Dietary Fibers in Modern Food Production: A Special Perspective with _-Glucans. In Biopolymers for Food Design; Grumezescu, A.M., Holban, A.M., Eds.; pp. 125–156, ISBN 978-0-12-811449-0.
*	Albertini, M.-V.; Carcouet, E.; Pailly, O.; Gambotti, C.; Luro, F.; Berti, L. 2006. Changes in organic acids and sugars during early stages of development of acidic and acidless citrus fruit. J. Agric. Food Chem. 54, 8335–8339.
*	Alonso, J., Desmarchelier, C. 2014. Plantas medicinales autóctonas de la Argentina: bases científicas para su aplicación en atención primaria de la salud. 1a ed. CABA: Corpus Libros Médicos y Científicos, 748 p.
*	Apel, M.A., Sobral, M., Menut, C., Bassiere, J.M., Zuanazzi, J.A., Schapoval, E.E.S. 2005. Volatil constituents of four Hexachlamys species growing in South Brazil. Flavour and fragrance journal, 20, 176–179.
*	Arena, M. E., Povilonis, I. S., Borroni, V., Pérez, E., Pellegrino, N., Cacciatore, C., Radice, S., 2023. Changes in Carbohydrates, Organic Acids, and Minerals at Different Development Stages of Hexachlamys edulis Fruit, a Wild South American Species with Horticultural Potential. Horticulturae. 9 3, 314. URL: doi.org/10.3390/horticulturae9030314
*	Arena, M.E., Curvetto, N., 2008. Berberis buxifolia fruiting: kinetic growth behavior and evolution of chemical properties during the fruiting period and different growing seasons. Sci. Hortic. 118, 120–127.
*	Arena, M.E., Postemsky, P., Curvetto, N.R., 2012. Accumulation patterns of phenolic compounds during fruit growth and ripening of Berberis buxifolia, a native Patagonian species. N. Z. J. Bot. 50 (1), 15–28.
*	Arena, M.E., Povilonis, I.S., Borroni, V., Constenla, D., Radice, S. 2021. Changes in physicochemical properties at different development stages of Hexachlamys edulis fruit, an underutilized South American species. Heliyon 7, e08323.
*	Arts, I.C. & Hollman P.C. 2005. Polyphenols and disease risk in epidemiologic studies. Am.J.Clin.Nutr. 81: 317–325.
*	Arturi, M.F. & Juarez, M. C., 1997. Composición de las comunidades arbóreas de la Isla Martín García en relación a un gradiente ambiental. Ecología Austral: 7, 65–72.
*	Aslam, M.M.; Deng, L.; Wang, X.; Wang, Y.; Pan, L.; Liu, H.; Niu, L.; Lu, Z.; Cui, G.; Zeng, W.; et al. 2019. Expression patterns of genes involved in sugar metabolism and accumulation during peach fruit development and ripening. Sci. Hortic. 257, 108633.
*	Baccichet, I.; Chiozzotto, R.; Bassi, D.; Gardana, C.; Cirilli, M.; Spinardi, A. 2021. Characterization of fruit quality traits for organic acids content and profile in a large peach germplasm collection. Sci. Hortic. 278, 109865.
*	Bae, H.; Yun, S.K.; Jun, J.H.; Yoon, I.K.; Nam, E.Y.; Kwon, J.H. 2014. Assessment of organic acid and sugar composition in apricot, plumcot, plum, and peach during fruit development. J. Appl. Bot. Food Qual. 87, 24–29.
*	Baillie, I. C. 2001. Soil survey staff 1999, soil taxonomy: a basic system of soil classification for making and interpreting soil surveys, agricultural handbook 436, Natural Resources Conservation Service, USDA, Washington DC, USA, 869.
*	Barrett, A., & Brown, L. 2021. Effects of rainfall, temperature and photoperiod on the phenology of ephemeral resources for selected bushveld woody plant species in southern Africa. Plos one, 16 5, e0251421.
*	Barua, U.; Das, R.P.; Gogoi, B.; Baruah, S.R. 2019. Underutilized fruits of Assam for livelihood and nutritional security. Agric. Rev. 40, 175–184.
*	Batista, W. B., Rolhauser, A. G., Biganzoli, F., Burkart, S. E., Goveto, L., Maranta, A., Pignataro, A., Genoveva Morandeira, N. S., & Rabadán, M., 2014. Las comunidades vegetales de La Sabana del Parque Nacional El Palmar (Argentina). Darwiniana, nueva serie, 2 1 , 5–38. URL: www.scielo.org.ar/scielo.php?script=sci_arttext&pid=S0011–67932014000100001&lng=es&tlng=en
*	Beardsell, D.V., Obrien, S.P., Williams, E.G., Knox, R.B., Calder, D.M. 1993. Reproductive biology of australian Myrtaceae. Australian Journal of Botany,41 5, 511–526.
*	Belhadj, F., Somrani, I., Aissaoui, N., Messaoud, C., Boussaid, M., Marzouki, M.N., 2016. Bioactive compounds contents, antioxidant and antimicrobial activities during ripening of Prunus persica L. varieties from the North West of Tunisia. Food Chem. 204, 29–36.
*	Belwal, T., Pandey, A., Bhatt, I.D., Rawal, R.S., Luo, Z., 2019. Trends of polyphenolics and anthocyanins accumulation along ripening stages of wild edible fruits of Indian Himalayan region. Sci. Rep. 9, 5894.
*	Bertucci, A., Haretche, F., Olivaro, C., Vázquez, A. 2008. Prospección química del bosque en galería de río Uruguay. Revista Brasileira de Farmacognosia, 18(1): 21–25.
*	Borges, L.L., Conceição, E.C., Silveira, D. 2014. Active compounds and medicinal properties of Myrciaria genus. Food Chemistry, 153: 224–233.
*	Bouvet, J.P. 2011. Relevamiento y evaluación de hospederos comerciales y silvestres de moscas de la fruta de importancia cuarentenaria. Informe Proyecto PNFRUO52851 INTA.
*	Bradley, N. L., Leopold, A. C., Ross, J., & Huffaker, W. 1999. Phenological changes reflect climate change in Wisconsin. Proceedings of the National Academy ofSciences, 96 17, 9701–9704.
*	Branco, I.G., Kikuchi, T.T., Sanjinez Argandona, E.J., Freitas Moraes, I.C., Haminiuk, C.W.I. 2016. Drying kinetics and quality of uvaia (Hexachlamys edulis (O. Berg)) powder obtained by foam–mat drying. International Journal of Food Science and Technology, 51: 1703–1710.
*	Brauch, J.E., 2016. Underutilized fruits and vegetables as potential novel pigment sources. In: Carle, R., Schweiggert, R. (Eds.), Handbook on Natural Pigments in Food and Beverages: Industrial Applications for Improving Food Color, Cambrige. Woodhead Publishing, pp. 305–335.
*	Britton, G.; Khachik, F. 2009. Carotenoids in Food. In Carotenoids: Nutrition and Health; Britton, G., Pfander, H., Liaaen–Jensen, S., Eds.; Birkhäuser: Basel, Switzerland; Volume 5, pp. 45–66, ISBN 978–3–7643–7501–0.
*	Camelo Munevar, D.O. 2016. Contribución al estudio fitoquímico de frutos de Syzygium paniculatum G. y evaluación de su actividad antioxidante. Revista, 48: 1–48.
*	Carnelossi, M.A.G.; Costa de Sena, H.; Narain, N.; Yaguiu, P.; da Silva, G.F. 2009. Physico–Chemical Quality Changes in Mangaba (Hancornia speciosa gomes) Fruit Stored at Different Temperatures. Braz. Arch. Biol. Technol. 52, 985–990.
*	Carrere, R. 2008. El ubajai (Hexachlamis edulis): un árbol frutal indígena. URL: www.guayubira.org.uy/monte/Ubajai.pdf.
*	Casas, R. R., & Albarracin, G. F., 2015. El deterioro del suelo y del ambiente en la Argentina (Tomo I). Editorial Prosa.
*	Castrejón, A.D.R., Eichholz, I., Rohn, S., Kroh, L.W., Huyskens–Keil, S., 2008. Phenolic profile and antioxidant activity of highbush blueberry (Vaccinium corymbosum L.) during fruit maturation and ripening. Food Chem. 109 (3), 564–572.
*	Cecotto, J.A., Taiariol, D.R., Cáceres, S. 2007. Colección de frutos tropicales de la EEA INTA Bella Vista. Publicación Técnica Nº 21.
*	Celik, H., Ӧzgen, M., Serce, S., Kaya, C., 2008. Phytochemical accumulation and antioxidant capacity at four maturity stages of cranberry fruit. Sci. Hortic. 117, 345–348.
*	Celli, G.B., Pereira–Netto, A.B., Beta, T. 2010. Comparative analysis of total phenolic content, antioxidant activity, and flavonoids profile of fruits from two varieties of brazilian cherry (Eugenia uniflora L.) throughout the fruit developmental stages. Food Research International, 44: 2442–2451.
*	Chebez, J.C., Masariche, M., 2010. Nuestros árboles. Trees of Argentina, 1 ed. Albatros, Buenos Aires, Argentina, p. 128.
*	Chervin, C. 2020. Should Starch Metabolism Be a Key Point of the Climacteric vs. Non–climacteric Fruit Definition? Front. Plant Sci. 11, 609189.
*	Cho, L. H., Yoon, J., & An, G. 2017. The control of flowering time by environmental factors. The Plant Journal, 90 4, 708–719.
*	Chuine, I., & Beaubien, E. G. 2001. Phenology is a major determinant of tree species range. Ecology Letters, 4 5, 500–510.
*	COI, Consejo Oleícola Internacional, 2009. Determinación de los biofenoles de los aceites de oliva mediante HPLC, 29. COI/T.20/Doc.N.º.
*	Colaric, M.; Stampar, F.; Solar, A.; Hudina, M. 2006. Influence of branch bending on sugar, organic acid and phenolic content in fruits of ‘Williams’ pears (Pyrus communis L.). J. Sci. Food Agric. 86, 2463–2467.
*	Cruz, F., Turchetto–Zolet, A., Veto, N., Mondin, C., Almerão, M., Margis, R. 2011. Molecular Phylogenetics of the genus Hexachlamys (Myrtaceae) using chloroplast and nuclear markers. BMC Proceedings, 5(7): 1–6.
*	Czech, A.; Zarycka, E.; Yanovych, D.; Zasadna, Z.; Grzegorczyk, I.; Kłys, S. 2020. Mineral content of the pulp and peel of various citrus fruit cultivars. Biol. Trace Elem. Res. 193, 555–563.
*	Da Cruz, F. 2012. Sistemática e filogenética molecular do genero Hexachlamys (Myrtaceae) a través do uso de marcadores plastidiais e nucleares. Tesis de Doctorado Universidad Fệderal do Rio Grande, 71 p.
*	Dandin, S.B., Krishna Kumar, N.K. 2016. Neglected and underutilized fruit species: an insurance against global mal and undernutrition. Regional Expert Consultation of NUS, 2016 FAO Regional Office, Bangkok.
*	Dandin, S.B., Krishna Kumar, N.K., 2016. Neglected and Underutilized Fruit Species: an Insurance against Global Mal and under Nutrition. http://www.fao.org/fileadmin/templates/rap/files/meetings/2016/161203_session1_4.pdf. (Último acceso 7 de abril de 2020).
*	de Lange, E., Sze, J.S., Allan, J. et al., 2023. A global conservation basic income to safeguard biodiversity. Nat Sustain. URL: doi.org/10.1038/s41893–023–01115–7
*	Dematte, M.E.R.P. 1997. Ornamental use of Brazilian Myrtaceae. Acta Horticulturae, 452: 166 p.
*	Desnoues, E.; Gibon, Y.; Baldazzi, V.; Signoret, V.; Génard, M.; Quilot–Turion, B. 2014. Profiling sugar metabolism during fruit development in a peach progeny with different fructose–to–glucose ratios. BMC Plant Biol. 14, 336.
*	Di Nicolantonio, J.J.; Liu, J.; O’Keefe, J.H. 2018. Magnesium for the prevention and treatment of cardiovascular disease. Open Heart 5, e000775.
*	Duguma, D. W., Law, E., Shumi, G. et al., 2023. Spatial predictions for the distribution of woody plant species under different land–use scenarios in southwestern Ethiopia. Landsc Ecol 38, 1249–1263. URL: doi.org/10.1007/s10980–023–01614–0
*	EI–Zoghbi, M. 1994. Biochemical changes in some tropical fruits during ripening. Food Chem. 49, 33–37.
*	Feng, L., Nie, K., Jiang, H., Fan, W., 2019. Effects of lutein supplementation in age–related macular degeneration. PLoS One 14 (12), e0227048.
*	Fernandez–Orozco, R., Gallardo–Guerrero, L., Hornero–Méndez, D., 2013. Carotenoid profiling in tubers of different potato (Solanum sp.) cultivars: accumulation of carotenoids mediated by xanthophyll esterification. Food Chem. 141 (3), 2864–2872.
*	Ferreyra, R.M., Vi~na, S.Z., Mugridge, A., Chaves, A.R., 2007. Growth and ripening effects on antioxidant capacity on strawberry cultivar Selva. Sci. Hortic. 112, 27–32.
*	Finatto, T., Dos Santos, K. L., Steiner, N., Bizzocchi, L., Holderbaum, D. F., Ducroquet, J. P., & Nodari, R. O. 2011. Late–acting self–incompatibility in Acca sellowiana (Myrtaceae) 1. Australian journal of botany, 59 1, 53–60.
*	Fisher, J. C., Dallimer, M., Irvine, K.N. et al., 2023. Human well–being responses to species’ traits. Nat Sustain. URL: doi.org/10.1038/s41893–023–01151–3
*	Fleckinger, J. 1955. Phenologie et arboriculture frutiere. Bon Jardinier 1, 362–372.
*	Franceschini, M.C. 2000. Morfología de embriones y plántulas de especies leñosas del nordeste argentino. Bonplandia, 10(1–4): 143–154.
*	Gentry, A. H., 1982. Patterns of neotropical plant species diversity. Evolutionary Biology 15, 1–84.
*	González Vega, M.E. 2013. Chirimoya (Annona cherimola Miller), frutal tropical y subtropical de valores promisorios. Cultivos Tropicales, 34(3): 52–63.
*	González, S. 2003. Ritmos de follaje y floración en algunas plantas leñosas nativas. Agrociencia, 7(2): 27–38.
*	González–Agüero, M.; Tejerina Pardo, L.; Zamudio, M.S.; Contreras, C.; Undurraga, P.; Defilippi, B.G. 2016. The Unusual Acid–Accumulating Behavior during Ripening of Cherimoya (Annona cherimola Mill.) is Linked to Changes in Transcription and Enzyme Activity Related to Citric and Malic Acid Metabolism. Molecules 21, 398.
*	Gordon, A. 2012. Bioactive Compounds in Underutilized Tropical Fruits from Latin America. Ph.D. Dissertation, Universitäts–und Landesbibliothek, Bonn, Germany. Available online: https://nbn–resolving.org/urn:nbn:de:hbz:5n–29864 (Último acceso 2 de diciembre de 2022).
*	Gordon, A., Jungfer, E., da Silva, B.A., Maia, J.G.S., Marx, F., 2011. Phenolic constituents and antioxidant capacity of four underutilized fruits from the Amazon region. J. Agric. Food Chem. 59, 7688–7699.
*	Guavita–Vargas, J., Avellaneda–Torres, L.M., Solarte, M.E., Melgarejo, L.M., 2018. Carotenoides, clorofilas y pectinas durante la maduración de variedades de guayaba (Psidium guajava L.) de Santander, Colombia. Rev. Colomb. Ciencias Hortícolas 12 (2), 379–389.
*	Guesmi, B. 2021. Climate as the Major Factor Controlling Phenology. In Agrometeorology. IntechOpen.
*	Hammer O., Harper D. A. T., Ryan P. D., 2001. PAST: Paleontological Statistics software package for education and data analysis. Palaeontologia Electronica 4(1):1–9.
*	Hornero–Méndez, D., 2019. Occurrence of carotenoid esters in foods. In: Mercadante, A.Z. (Ed.), Carotenoid Esters in Foods: Physical, Chemical and Biological Properties. Royal Soc. Chem., Cambridge, UK, pp. 182–284.
*	Hornero–Méndez, D., Minguez–Mosquera, M.I., 2000. Xanthophyll esterification accompanying carotenoid over accumulation in chromoplast of Capsicum annuum ripening fruits is a constitutive process and useful for ripeness index. J. Agric. Food Chem. 48 (5), 1617–1622.
*	Hossain, M.M.; Rahim, M.A.; Haque, M.R. 2021. Biochemical properties of some important underutilized minor fruits. J. Agric. Food Res. 5, 100148.
*	Hussein, S.A.M., Hashem, A.N.M., Seliem, M.A., Lindequit, U., Nawwar, M.A.M. 2003. Polyoygenated flavonoids from Eugenia edulis. Phytochemistry, 64(4): 883–889.
*	Ikegaya, A.; Toyoizumi, T.; Ohba, S.; Nakajima, T.; Kawata, T.; Ito, S.; Arai, E. 2019. Effects of distribution of sugars and organic acids on the taste of strawberries. Food Sci. Nutr. 7, 2419–2426.
*	IPBES. 2019. Global assessment report of the Intergovernmental Science–Policy Platform on Biodiversity and Ecosystem Services, Brondízio, E. S., Settele, J., Díaz, S., Ngo, H. T. (eds). IPBES secretariat, Bonn, Germany. 1144 pages. ISBN: 978–3–947851–20–1.
*	Ivanova, V., Stefova, M., Vojnoski, B., Dö rnyei, A., Mark, L., D́ imovska, V., Stafilov, T., Kilar, F., 2011. Identification of polyphenolic compounds in red and white grape varieties grown in R. Macedonia and changes of their content during ripening. Food Res. Int. 44, 2851–2860.
*	Kader, A.A. 2008. Flavor quality of fruits and vegetables. J. Sci. Food Agric. 88, 1863–1868.
*	Kähkönen, M.P., Hopia, A.I., Heinonen, M., 2001. Berry phenolics and their antioxidant activity. J. Agric. Food Chem. 49, 4076–4082.
*	Kebede, M., & Isotalo, J. 2016. Flowering and fruiting phenology and floral visitation of four native tree species in the remnant moist Afromontane forest of Wondo Genet, south central Ethiopia. Tropical Ecology, 57 2.
*	Khan, A. U., Abbas, A., Sharif, F., Mansoor, A., Siddiq, Z., 2023. Conserving the threatened woody vegetation on dune slopes: Monitoring the decline and designing adaptive strategies for restoration. Nature Conservation 53: 165–182. URL: doi.org/10.3897/natureconservation.53.106406
*	Kinupp, V.F., De Barros, I.B.I. 2008. Protein and mineral contents of native species, potential vegetables, and fruits. Ciencia e Tecnologia de Alimentos, 28(4): 846–857.
*	Koppen W. 1936. Das geographische System der Klimate. In:Koppen W, Geiger R (eds) Handbuch der Klimato – logie. Gebruder Borntraeger, Berlin, 1−44
*	Köppen, W., 1936. Das geographisca system der Klimate. In: Köppen, W., Geiger, G. (Eds.), Handbuch der Klimatologie, pp. 1–44. Available at: http://koeppengeiger.vuwien.ac.at/pdf/Koppen_1936.pdf.
*	Kozel, C. 1991. Guia de medicina natural, Plantas medicinales, 2: 495 p.
*	Kuai, B., Chen, J., Hörtensteiner, S., 2018. The biochemistry and molecular biology of chlorophyll breakdown. J. Exp. Bot. 69 (4), 751–767.
*	Kunming – Montreal Global Biodiversity Framework CBD. 2022. URL: www.cbd.int/doc/c/e6d3/cd1d/daf663719a03902a9b116c34/cop–15–l–25–en.pdf
*	Lage–Yusty, M.; Simal–Lozano, J.; Gómez, G.S. 1983. Determinación de almidón en alimentos. Trab. Compostel. Biol. 10, 15–25.
*	Lamani, S.; Anu–Appaiah, K.A.; Murthy, H.N.; Dewir, Y.H.; Rikisahedew, J.J. 2022. Analysis of Free Sugars, Organic Acids, and Fatty Acids of Wood Apple (Limonia acidissima L.) Fruit Pulp. Horticulturae 8, 67.
*	Landrum, L.R., Kawasaki, M.L. 1997. The genera of Myrtaceae in Brazil: an illustrated synoptic treatment and identification keys.
*	Lattanzio, V., Kroon, P.A., Quideau, S., Treutter, D., 2008. Plant phenolics—secondary metabolites with diverse functions. In: Daayf, F., Lattanzio, V. (Eds.), Recent Advances in Polyphenol Research, 1. Wiley–Blackwell, Oxford, pp. 1–35.
*	Legrand, D. 1941. Lista Preliminar de las Mirtáceas Argentinas. Darwiniana, 5: 463–486.
*	Legrand, D. 1962. Lista actual de las mirtáceas de argentina. Boletín de la Sociedad Argentina de Botánica, 42.
*	Legrand, D., Klein, R.M. 1977. Mirtáceas: Campo–manesia, Feijoa, Britoa, Myrrhinium, Hexachlamys, Siphoneugena, Myrcianthes, Neomitranthes, Psidium. Reitz P.R. (org.). Flora Ilustrada Catarinense. Itajaí: Herbário Barbosa Rodrigues, 571–730 p.
*	Li, R.Y., Wang, S., McClements, D.J., Wan, Y., Liu, C.M., Fu, G.M., 2019. Antioxidant activity and α–amylase and α–glucosidase inhibitory activity of a fermented tannic acid product: Trigalloylglucose. LWT – Food Sci. Technol. 112, 108249.
*	Lio, M., Moriyama, A., Matsumoto, Y., Takaki, N., Fukumoto, M. 1985. Inhibition of Xanthine Oxidase by Flavonoids. Department of Food and Nutrition Science, Kumamoto Women’s University, Kenguncho, Kumamoto 862, Japan.
*	Llorente–Culebras, S., Ladle R. J., Santos A. M. C., 2023. Publication trends in global biodiversity research on protected areas, Biological Conservation, Volume 281, 2023, 109988, ISSN 0006–3207.
*	Lorca, G.G., AMAT, A.G., González, C. 1995. Análisis Comparativo de Caracteres Diagnósticos para la Identificación de Tres Especies Argentinas de Myrtaceae empleadas en la Medicina Popular. Acta Farm. Bonaerense, 14(2): 81–86.
*	Lou J., González–Oreja, J. A., 2012. Midiendo la diversidad biológica: más allá del índice de Shannon Acta zoológica lilloana 56 (1–2): 3–14.
*	Lughadha, E.N., Proença, C. 1996. A Survey of the Reproductive Biology of the Myrtoideae (Myrtaceae). Annals of the Missouri Botanical Garden, 83(4): 480–503.
*	Luo, L., Zhang, Y., & Xu, G. 2020. How does nitrogen shape plant architecture?. Journal of experimental botany, 71 15, 4415–4427.
*	Mabry, T.J., Markham, K.R., Thomas, M.B., 1970. The ultraviolet spectra of flavones and flavonols. In: Mabry, T.J., Markham, K.R., Thomas, M.B. (Eds.), The Systematic Identification of Flavonoids. Springer, Berlin, Heidelberg, pp. 41–164.
*	Makkar, H.P.S., Bluemmel, M., Borowy, N.K., Becker, K., 1993. Gravimetric determination of tannins and their correlations with chemical and protein precipitation methods. J. Sci. Food Agric. 61, 161–165.
*	Mao, Y.; Tian, S.; Qin, Y.; Cheng, S. 2021. An optimized organic acid human sensory sourness analysis method. J. Sci. Food Agric. 101, 5880–5887.
*	Marchiori, J.N.C., Dos Santos, S.R. 2010. Anatomía das madeiras de campomanesia aurea O. Berg e Eugenia myrcianthes Niedenzu (Myrtaceae). Balduinia, 22: 23–30.
*	Marchiori, S.S.R., Cardoso, J.N., Siegloch, A.M. 2014. Diversidade estrutural em Eugenia L. (Myrtaceae). Ciência Florestal, Santa Maria, 24(3): 785–792.
*	Mattera, M.G., Hornero–Méndez, D., Atienza, S.G., 2020. Carotenoid content in tritordeum is not primarily associated with esterification during grain development. Food Chem. 310, 125847.
*	Mazine, F.F., Quintino Faria, J.E., Giaretta, A., Vasconcelos, T., Forest, F., Lucas, E. 2018. Phylogeny and biogeography of the hyper–diverse genus Eugenia (Myrtaceae: Myrteae), with emphasis on E. sect. Umbellatae, the most unmanageable clade. Taxon, 67(4): 752–769.
*	Mazine, F.F., Souza, V.C., Sobral, M., Forest, F., Lucas, E. 2014. A preliminary phylogenetic analysis of Eugenia (Myrtaceae: Myrteae), with a focus on Neotropical species. Kew Bulletin, 69: 94–97.
*	McEwan, R. W., Brecha, R. J., Geiger, D. R., & John, G. P. 2011. Flowering phenology change and climate warming in southwestern Ohio. Plant Ecology, 212 1, 55–61.
*	Megazyme. 2017. Total Dietary Fiber. Assay Procedure. Available online: https://www.megazyme.com/documents/Assay_Protocol/K–TDFR–200A_DATA.pdf (Último acceso 10 de junio de 2023).
*	Meng, Z., Dong, J., Ellis, E.C. et al. (2023). Post–2020 biodiversity framework challenged by cropland expansion in protected areas. Nat Sustain. https://doi.org/10.1038/s41893–023–01093–w
*	Micou, A. P., 2003. Riesgo ambiental por invasiones biológicas en una zona con alto valor de conservación Las cuencas de El Palmar, Entre Ríos (Tesis de grado). Universidad de Buenos Aires, Buenos Aires, Argentina.
*	Mier, G.H.J., Cáez, R.G., 2011. Contenido de polifenoles, carotenos y capacidad antioxidante en frutos de uchuva (Physalis peruviana) en relación a su estado de maduración. ReCiTeIA v 11 (1b), 103–115.
*	Minguez–Mosquera, M.I., Hornero–Mendez, D., 1993. Separation and quantification of the carotenoid pigments in red peppers (Capsicum annuum L.), paprika, and oleoresin by reversed–phase HPLC. J. Agric. Food Chem. 41 (10), 1616–1620.
*	Mokhtar, S.I., Abd Aziz, N.A., 2015. Changes in physicochemical characteristics and organic acids during ripening of five tropical fruits species in Malaysia. J. Teknol. (Sci. Eng.) 77 (24), 119–122.
*	Molina, A.M. 2016. El Jardín Botánico Arturo E. Ragonese (JBAER): miradas a través del tiempo, realidad y prospectiva. Buenos Aires: Ediciones INTA, 185–186.
*	Murata, M., Tsurutani, M., Tomita, M., Homma, S., Kaneko, K., 1995. Relationship between apple ripening and browning: changes in polyphenol content and polyphenol oxidase. J. Agric. Food Chem. 43 (5), 1115–1121.
*	Murthy, H.N.; Bapat, V.A. 2020. Importance of Underutilized Fruits and Nuts. In Bioactive Compounds in Underutilized Fruits and Nuts; Murthy, H., Bapat, V., Eds.; Reference Series in Phytochemistry; Springer: Cham, Switzerland.
*	Nadeem, M.; Qureshi, T.M.; Ugulu, I.; Riaz, M.N.; An, Q.U.; Khan, Z.I.; Dogan, Y. 2019. Mineral, vitamin and phenolic contents and sugar profiles of some prominent date palm (Phoenix dactylifera) varieties of Pakistan. Pak. J. Bot. 51, 171–178.
*	Nandal, U., Bhardwaj, R.L. 2014. The role of underutilized fruits in nutritional and economic security of tribals: a review. Critical Reviews in Food Science and Nutrition, 54(7): 880–890.
*	Nápoles, R., 2016. Ecological Indexes for assessment anthropization – conservation of unit of vegetations, ecosystems, landscape and territory. Acta Botánica Cubana. 215 3, 328–335.
*	Natella, F., Nardini, M., Di Felice, M., Scaccini, C., 1999. Benzoic and cinnamic acid derivatives as antioxidants: structureáctivity relation. J. Agric. Food Chem. 47 4, 1453–1459.
*	Nitcheu, Ngemakwe P.H., Remize, F., Thaoge, M.L., Sivakumar, D., 2017. Phytochemical and nutritional properties of underutilized fruits in the southern African region. South Afr. J. Bot. 113, 137–149.
*	Nyeki, J., & Soltesz, M. 1996.Floral biology of temperate zone fruit trees and small fruits. Akademiai Kiado.
*	Oliveira–Filho, A. T., 2017. NeoTropTree, Flora arbórea da Região Neotropical: Um banco de dados envolvendo biogeografia, diversidade e conservação. Universidade Federal de Minas Gerais.
*	Oroño, L.E., Albornoz Medina, P., Núñez Campero, S., Van Nieuwenhove, G.A., Bezdjian, L.P., Martin, C.B., Schliserman, P., Ovruski, S.M. 2006. Update of host plant list of Anastrepha fraterculus and Ceratitis capitata in Argentina. Fruit Flies of Economic Importance: From Basic to Applied Knowledge. Proceedings of the 7th International Symposium on Fruit Flies of Economic Importance, Salvador, Brazil.
*	Osorio, S.; Scossa, F.; Fernie, A.R. 2013. Molecular regulation of fruit ripening. Front. Plant Sci. 14, 198.
*	Pareek, S. 2016. Chapter 17—Nutritional and Biochemical Composition of Lychee (Litchi chinensis Sonn.) Cultivars. In Nutritional Composition of Fruit Cultivars; Simmonds, M.S.J., Preedy, V.R., Eds.; pp. 395–418, ISBN 9780124081178.
*	Pareek, S., Sagar, N.A., Sharma, S., Kumar, V., Agarwal, T., González–Aguilar, G.A., Yahia, E.M., 2018. In: Yahia, E.M. (Ed.), Fruit and Vegetable Phytochemicals: Chemistry and Human Health, second ed., I. John Wiley & Sons, Oxford, UK.
*	Paul, V.; Pandey, R.; Ramesh, K.V.; Singh, A. 2012. Role of mineral nutrients in physiology, ripening and storability of fruits. In Advances in Plant Physiology; Hemantaranjan, A., Ed.; An International Treatise Series: Nutriophysiological and Molecular Interventions for crop improvement under changing climate; pp. 56–96.
*	Peel, M.C., Finlayson, B.L., McMahon, T.A., 2007. Updated world map of the K€oppen–Geiger climate classification. Hydrol. Earth Syst. Sci. 11, 1633–1644.
*	Pereira, M.C., Steffens, R.S., Jablonski, A., Hertz, P.F., de O. Rios, A., Vizzotto, M., Flores, S.H., 2012. Characterization and antioxidant potential of Brazilian fruits from the Myrtaceae family. J. Agric. Food Chem. 60 (12), 3061–3067.
*	Perelman, S. B., & Puhl, L. E., 2023. Abordaje multivariado en estudios botánicos y ecológicos. Darwiniana, Nueva Serie, 11(1), 272–294. URL: doi.org/10.14522/darwiniana.2023.111.1086
*	Petrovska, B.B. 2012. Historical review of medicinal plants’ usage. Pharmacognosy reviews, 6 11, 1.
*	Posit team. 2023. RStudio: Integrated Development Environment for R. Posit Software, PBC, Boston, MA. Recuperado de http://www.posit.co/
*	Pound, L. M., Wallwork, M. A. B., Potts, B. M., & Sedgley, M. 2002. Selfincompatibility in Eucalyptus globulus ssp. globulus (Myrtaceae). Australian Journal of Botany, 50 3, 365–372.
*	Povilonis, I.S.; Arena, M.E.; Radice, S. 2021. Caracterización de la variabilidad fenotípica de los frutos de ubajay (Hexachlamys edulis). In Proceedings of the 41_ Congreso Argentino de Horticultura, La Plata, Argentina, 5–8 October; Available online: http://sedici.unlp.edu.ar/bitstream/handle/10915/128494/Documento_completo.pdf–PDFA.pdf?sequence=1&isAllowed=y (Último acceso 15 de noviembre de 2022).
*	Povilonis, I.S.; Arena, M.E.; Radice, S. 2021. Hexachlamys edulis (Berg) Kausel & Legrand, “ubajay”, a native fruit species from South America. AHS 35, 389–397. doi.org/10.36253/ahsc–10660
*	Powell, B., Haraksingh Thilsted, S., Ickowitz, A., Termote, C., Sunderland, T., Herforth, A., 2015. Improving diets with wild and cultivated biodiversity from across the landscape. Food Secur. 7, 535–554.
*	Proença, C.E.B. 2006. Proposal to Conserve the Name Myrcianthes edulis against Psidium amygdalinum (Myrtaceae). Taxon, 55(2): 536–537.
*	Prusky, D., Keen, N.T., 1993. Involvement of preformed antifungal compounds in the resistance of subtropical fruits to fungal decay. Plant Dis. 77, 114–119.
*	Puccio, S., Perrone, A., Sortino, G., Gianguzzi, G., Gentile, C., Farina, V., 2019. Yield, pomological characteristics, bioactive compounds and antioxidant activity of Annona cherimola Mill. grown in mediterranean climate. AIMS Agric. Food. 4 (3), 592–603.
*	Pulido, R., Bravo, L., Saura–Calixto, F., 2000. Antioxidant activity of dietary polyphenols as determined by a modified ferric reducing/antioxidant power assay. J. Agric. Food Chem. 48 (8), 3396–3402.
*	Putruele, M.T.G. 1996. Hosts for Ceratitis capitata and Anastrepha fraterculus in the Northeastern Province of Entre Ríos, Argentina. En BA Mc Pheron y GJ Steck (eds). Fruit fly pests: a world assessment of their biology and management. St. Lucie, Delray Beach.
*	Quintavalle, G. 2020. Estudios preliminares en la especie frutal nativa de Argentina Hexachlamys edulis (O. Berg) Kausel & D. Legrand "Ubajay" para su valoracion como alternativa productiva y como alimento funcional. Graduation thesis. Escuela Superior de Ingenieria, Informatica y Cs. Agroalimentarias. Universidad de Moron
*	R Core Team (2023). _R: A Language and Environment for Statistical Computing_. R Foundation for Statistical Computing, Vienna, Austria. <https://www.R–project.org/>.
*	Radice S. 2005. Biologia floral y reproductiva del cultivar Forastero (Prunus persica [L] Batsch.) Rosaceae, Prunoideae, en estiones crecidos sobre pies francos o clonales macro y micropropagados. PhD Thesis. Facultad de Ciencias Exactas y Naturales, UBA.
*	Radice, S., & Arena, M. E. 2014. Environmental effect on the leaf morphology and anatomy of Berberis microphylla G. Forst. International Journal of Plant Biology, 6 1, 5677.
*	Radice, S., & Arena, M. E. 2018. Reproductive shoots of Berberis microphylla G. Forst. in relation with the floral bud development and the fruit set. Heliyon, 4 11, e00927.
*	Radice, S., Alonso, M. & Arena, M.E. 2018. Berberis microphylla: A species with Phenotypic Plasticity in Different Climatic Conditions. International Journal of Agricultural Biology 20, 2221‒2229..
*	Radice, S.; Povilonis, I.S.; Arena, M.E. 2023. Flower and fruit formation of Hexachlamys edulis in Buenos Aires, Argentina. JAEID 117 1, 21 – 38. DOI: 10.36253/jaeid–13261
*	Rahman, M.M.; Roy, M.; Sajib, M.A.M.; Sarkar, A.; Hussain, M.S. 2015. Radiation effects on essential minerals content of cucumber (Cucumis sativus). Amer. J. Food Nutr. 3, 69–74.
*	Richardson, D. M. and Rejmánek, M., 2011, Trees and shrubs as invasive alien species – a global review. Diversity and Distributions, 17, 788–809. URL: doi.org/10.1111/j.1472–4642.2011.00782.x
*	Robards, K., 2003. Strategies for the determination of bioactive phenols in plants, fruit and vegetables. J. Chromatogr. A 1000 (1–2), 657–691.
*	Rodriguez, J., Loyola, J., Schmeda–Hirschmann, G. 1992. Hypoglycaemic Activity of Hexachlamys edulis ('Yvahai') Extract in Rats. Phytotherapy research, 6: 47–49.
*	Rogiers, S.Y.; Knowles, N.R. 1997. Physical and chemical changes during growth, maturation, and ripening of Saskatoon (Amelanchier alnifolia) fruit. Can. J. Bot. 75, 1215–1225.
*	Romagnolo, M.B., Conceição de Souza, M. 2004. Os gêneros Calycorectes O. Berg, Hexachlamys O. Berg, Myrcianthes O. Berg, Myrciaria O. Berg e Plinia L. (Myrtaceae) na planície alagável do alto rio Paraná, Brasil. Acta bot. bras., 18(3): 613–627.
*	Rotman, A. D. 1982. Los generos Calycorectes, Hexachlamys, Myrciaria, Paramyrciaria, Plinia y Siphoneugena en la flora argentina.(Myrtaceae). Darwiniana, 157–185.
*	Rotman, A.D. 1982. Los géneros Calycorectes, Hexachlamys, Myrciaria, Paramyrciaria, Plinia y Siphoneugena en la flora argentina (Myrtaceaea). Darwiniana, 24(1–4): 157–185.
*	Roussos, P.A., Denaxa, N.–K., Damvakaris, T., 2009. Strawberry fruit quality attributes after application of plant growth stimulating compounds. Sci. Hortic. 119, 138–146.
*	S Ajay Vino, H., Sinija, V.R. 2016. Underutilized fruits in Indian. Indian Food Industry Magazine, 35(2): 45–46.
*	S Ajay Vino, H., Sinija, V.R., 2016. Underutilized fruits in Indian. IFI Mag 35 (2), 45–46.
*	Saini, R.K., Nile, S.H., Park, S.W., 2015. Carotenoids from fruits and vegetables: chemistry, analysis, occurrence, bioavailability and biological activities. Food Res. Int. 76, 735–750.
*	Salminen, J.P., Ossipov, V., Loponen, J., Haukioja, E., Pihlaja, K., 1999. Characterisation of hydrolysable tannins from leaves of Betula pubescens by high–performance liquid chromatography–mass spectrometry. J. Chromatogr. A 864 (2), 283–291.
*	Schmeda–Hirschmann, G. 1995. Flavonoids from Calycorectes, Campomanesia, Eugenia and Hexachlamys species. Fitoterapia, 66(4): 373–374.
*	Schmeda–Hirschmann, G., Zúñiga, J., Dutra–Behrens, M., Habermehl, G. 1996. Xanthine Oxidase Inhibitory Activity of Flavonoids and Tannins from Hexachlamys edulis (Myrtaceae). Planta Medica, 62(5): 466–467.
*	Scranton, K., & Amarasekare, P. 2017. Predicting phenological shifts in a changing climate. Proceedings of the National Academy of Sciences, 11 50, 13212–13217.
*	Shannon, C. & Weaver, W., 1949. The mathematical theory of communication. University of Illinois Press, Urbana–USA.
*	Shi, Y.; Li, B.J.; Su, G.; Zhang, M.; Grierson, D.; Chen, K.S. 2022. Transcriptional regulation of fleshy fruit texture. J. Integr. Plant Biol. 64, 1649–1672.
*	Shimada, K., Fujikawa, K., Yahara, K., Nakamura, T., 1992. Antioxidative properties of Xanthan on the autoxidation of soybean oil in cyclodextrin emulsion. J. Agric. Food Chem. 6, 945–948.
*	Shmida, A., & Wilson, M. V., 1985. Biological Determinants of Species Diversity. Journal of Biogeography, 12(1), 1–20. URL: doi.org/10.2307/2845026
*	Silva, N.A.D., Rodrigues, E., Mercadante, A.Z., de Rosso, V.V., 2014. Phenolic compounds and carotenoids from four fruits native from the Brazilian Atlantic forest. J. Agric. Food Chem. 62 22, 5072–5084.
*	Siriwoharn, T., Ronald, E.W., Chad, E.F., Pereira, C.B., 2004. Influence of cultivar, maturity, and sampling on blackberry (Rubus L. Hybrids) anthocyanins, polyphenolics, and antioxidant properties. Food Chem. 52 26, 8021–8030.
*	SMN. 2023. Servicio Meteorológico Nacional. Argentina.
*	Solymosi, K., Mysliwa–Kurdziel, B., 2017. Chlorophylls and their derivatives used in food industry and medicine. Mini Rev. Med. Chem. 17 13, 1194–1222.
*	Song, J.; Bi, J.; Chen, Q.; Wu, X.; Lyu, Y.; Meng, X. 2019. Assessment of sugar content, fatty acids, free amino acids, and volatile profiles in jujube fruits at different ripening stages. Food Chem. 270, 344–352.
*	Spann, T. M., & Schumann, A. W. 2010. Mineral nutrition contributes to plant disease and pest resistance. EDIS, 2010 4.
*	Stafussa, A.P., Maciel, G.M., Rampazzo, V., Bona, E., Makara, C.N., Junior, B.D., Haminiuk, C.W.I., 2018. Bioactive compounds of 44 traditional and exotic Brazilian fruit pulps: phenolic compounds and antioxidant activity. Int. J. Food Prop. 21 1, 106–118.
*	Stevens, P.F. 2017. Angiosperm Phylogeny Website. Version 14.
*	Suwardi, A. B. & Navia, Z. I., 2023. Sustainable Use and Management of Wild Edible Fruit Plants: A Case Study in the Ulu Masen Protected Forest, West Aceh, Indonesia, Journal of Sustainable Forestry, 42 8, 811–830. URL: doi.org/10.1080/10549811.2022.2123355
*	Taghavi, T.; Siddiqui, R.; Rutto, L.K. 2019. The effect of preharvest factors on fruit and nutritional quality in strawberry. In Strawberry Pre– and Post–harvest Management Techniques for Higher Fruit Quality; IntechOpen: London, UK.
*	Taiz, L., Zeiger, E., Moller, I. M., & Murphy, A. 2015. Plant physiology and development (No. Ed. 6). Sinauer Associates Incorporated.
*	Takao, L.K., Imatomi, M., Gualtieri, S.C.J. 2015. Antioxidant activity and phenolic content of leaf infusions of Myrtaceae species from Cerrado (Brazilian Savanna). Brazilian Journal of Biology, 75 4: 948–952.
*	The Forests, Trees and Agroforestry Partnership. 2022. URL: www.foreststreesagroforestry.org/wp–content/uploads/2022/10/The–FTA–Partnership–Charter.pdf
*	Theoduloz, C., Franco, L., Ferro, E., Schmeda Hirschmann, G. 1998. Xanthine oxidase inhibitory activity of Paraguayan Myrtaceae. Journal of Ethnopharmacology, 24 (2–3): 179–183.
*	Trad, M.; Boge, M.; Hamda, H.B.; Renard, C.M.G.C.; Harbi, M. 2017. The Glucose–Fructose ratio of wild Tunisian grapes. Cogent Food Agric. 3, 1374156.
*	Tyagi, S.; Sahay, S.; Imran, M.; Rashmi, K.; Mahesh, S.S. 2017. Pre–harvest factors influencing the postharvest quality of fruits: A review. Curr. J. Appl. Sci. Technol. 23, 12.
*	Ulloa, W., C. M. Baeza, V. L. Finot, A. Marticorena & E. Ruiz., 2011. Micromorfología de la lemma de los géneros Polypogon, Agropogon y Agrostis (Poaceae) en Chile. Journal of the Botanical Research Institute of Texas 5(1):237–253.
*	UNEP–WCMC and IUCN. 2023. Protected Planet: The World Database on Protected Areas (WDPA) and World Database on Other Effective Area–based Conservation Measures (WD–OECM) [Online], July 2023, Cambridge, UK: UNEP–WCMC and IUCN. Available at: www.protectedplanet.net.
*	Vicente, A.R.; Manganaris, G.A.; Sozzi, G.O.; Crisosto, C.H. 2009. Nutritional quality of fruits and vegetables. In Postharvest Handling: A Systems Approach, 2nd ed.; Florkowski,W.J., Shewfelt, R.L., Brueckner, B., Prussia, S.E., Eds.; 57–106, ISBN 978–0–12–374112–7.
*	Viglizzo, E. F., & Jobbágy, E., 2010. Expansión de la Frontera Agropecuaria en Argentina y su Impacto Ecológico–Ambiental. Ediciones INTA, 9–16.
*	Vignale, B., Bisio, L. 2005. Selección de frutales nativos en Uruguay. Agrociencia, 9 1–2, 41–51.
*	Walker, R.P.; Famiani, F. 2018. Organic Acids in Fruits: Metabolism, Functions and Contents. In Horticultural Review, 1st ed.;Warrington, I., Ed.; pp. 371–430, ISBN 978–1–119–43107–7.
*	Wang, H.;Wang, J.; Mujumdar, A.S.; Jin, X.; Liu, Z.L.; Zhang, Y.; Xiao, H.W. 2021. Effects of postharvest ripening on physicochemical properties, microstructure, cell wall polysaccharides contents (pectin, hemicellulose, cellulose) and nanostructure of kiwifruit (Actinidia deliciosa). Food Hydrocoll. 118, 106808.
*	Ward, J. H., 1963. Hierarchical grouping to optimize an objective function. J. Amer. Stat. Assoc. 58, 236–244.
*	Whittaker, R. H., 1977. Evolution of species diversity in land communities, Evol. Bioi. 10, 1–87.
*	WHO. 2012. Potassium Intake for Adults and Children; WHO: Geneva, Switzerland, pp. 1–52, ISBN 978–92–4–150482–9. Available online: https://www.who.int/publications/i/item/9789241504829 (Último acceso 20 de enero de 2023).
*	Wongmetha, O., Kec, L.–S., Liang, Y.–S., 2015. The changes in physical, bio–chemical, physiological characteristics and enzyme activities of mango cv. Jinhwang during fruit growth and development. NJAS – Wageningen J. Life Sci. 72–73, 7–12.
*	World Bank. 2023. Recuperado de www.worldbank.org/
*	World Health Organization. 2004. Vitamin and Mineral Requirements in Human Nutrition; World Health Organization: Geneva, Switzerland. Available online: https://www.fao.org/3/y2809e/y2809e00.htm (Último acceso 20 de enero de 2023).
*	WWF. 2020. Living planet report – bending the curve of biodiversity loss. Gland, Switzerland. Recuperado de www.wwf.ch/de/
*	Xie, F.; Chen, C.; Chen, J.; Yuan, Y.; Hua, Q.; Zhang, Z.; Zhao, J.; Hu, G.; Chen, J.; Qin, Y. 2022. Metabolic Profiling of Sugars and Organic Acids, and Expression Analyses of Metabolism–Associated Genes in Two Yellow–Peel Pitaya Species. Plants 11, 694.
* Thornhill Andrew H., Hope Geoff S., Craven Lyn A., Crisp Michael D. (2012) Pollen morphology of the Myrtaceae. Part 4: tribes Kanieae, Myrteae and Tristanieae. Australian Journal of Botany 60, 260-289.
*	Zhang, W.; Lunn, J.E.; Feil, R.; Wang, Y.; Zhao, J.; Tao, H.; Guo, Y.; Zhao, Z. 2017. Trehalose 6–phosphate signal is closely related to sorbitol in apple (Malus domestica Borkh. cv. Gala). Biol. Open 6, 260–268.
*	Zhao, A.–L.; Xue, X.–F.; Wang, Y.–K.; Sui, C.–L.; Ren, H.–Y.; Li, D.–K. 2016. The Sugars and Organic Acids Composition in Fruits of Different Chinese Jujube Cultivars of Different Development Stages. Acta Hortic. Sin. 43, 1175–1185.
*	Zhi,W.S.; Li, Y.F.; Zi, S.W.; Xue, X.B. 2004. Sugar transport, metabolism, accumulation and their regulation in fruits. J. Plant Physiol. Mol. Biol. 30, 1–10.
*	Zunzunegui, M., Ain–Lhout, F., Barradas, M. D., Alvarez–Cansino, L., Esquivias, M. P., & Novo, F. G. 2009. Physiological, morphological and allocation plasticity of a semi–deciduous shrub. Acta Oecologica, 35 3, 370–379.
