---
title: "Branches"
---

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)


# branches<-read_excel("database.xlsx", sheet="branches")
library(readxl)
branches <- read_excel("database.xlsx", sheet="branches")

branches$year<-factor(branches$year,levels=c("2019","2021","2022"))
branches$site<-factor(branches$site,levels=c("concordia", "palmar","gualeguaychu"))
branches$phenotype<-as.factor(branches$phenotype)
branches$branch <-factor(branches$branch,levels=c("N", "S","E","O"))

branches$PFF <- as.numeric(branches$PFF)

# branches_19<-subset(branches, year == "2019")
# branches_21<-subset(branches, year == "2021")
# branches_22<-subset(branches, year == "2022")

```

## Descriptive table
```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

branches_vr <- names(branches)
branches_vr <- branches_vr[-c(1:4)]

library(dplyr)

branches_summary <- branches %>%
  group_by(year, site) %>%
  summarise_at(vars((branches_vr)), 
               funs(mean = mean(., na.rm=TRUE)
                    ))


# branches_length<- branches %>%
#   group_by(site, year) %>%
#   summarise(
#     n = n(),
#     mean = mean(length, na.rm=TRUE),
#     min = min(length, na.rm=TRUE),
#     max = max(length, na.rm=TRUE),
#     sd = sd(length, na.rm=TRUE)
#   )
# 
# branches_length

branches_summary

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)

g<-ggplot(data=branches_summary, aes(x=site, y=mean, fill=site))+
  stat_summary(fun = "mean", size = 1, geom = "bar") +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd),
                width=.2, position=position_dodge(.9))+
  facet_grid(.~year)+
  labs(x="", y="")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
  scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
  theme(legend.title=element_blank())+
  theme(legend.position='none')+
  theme(panel.grid.major.y = element_line(color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='black'))+
  theme(axis.text = element_text(color='black'))


```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(tidyr)
library(ggplot2)
library(ggpubr)

# Convertir los datos de ancho a largo
branches_summary_long <- gather(branches_summary, variable, value, -site, -year)

branches_summary_long_1 <- branches_summary_long[-c(1:36),]
branches_summary_long_2 <- branches_summary_long[-c(37:72),]
branches_summary_long_3 <- branches_summary_long[-c(73:108),]
branches_summary_long_4 <- branches_summary_long[-c(109:144),]

# Crear una lista de gráficos
plots1 <- lapply(unique(branches_summary_long_1$variable), function(var) {
  ggplot(data = branches_summary_long[branches_summary_long$variable == var,], 
         aes(x = site, y = value, fill = site)) +
    stat_summary(fun = "mean", size = 1, geom = "bar") +
    facet_wrap(~year, ncol = 2, scales = "free_x") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
    scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
    theme(legend.title = element_blank()) +
    theme(legend.position = 'none') +
    theme(panel.grid.major.y = element_line(color = 'black')) +
    theme(panel.grid.major.x = element_blank()) +
    theme(text = element_text(size = 10, color = 'black')) +
    theme(axis.text = element_text(color = 'black')) +
    labs(title = var)
})

plots2 <- lapply(unique(branches_summary_long_2$variable), function(var) {
  ggplot(data = branches_summary_long[branches_summary_long$variable == var,], 
         aes(x = site, y = value, fill = site)) +
    stat_summary(fun = "mean", size = 1, geom = "bar") +
    facet_wrap(~year, ncol = 2, scales = "free_x") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
    scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
    theme(legend.title = element_blank()) +
    theme(legend.position = 'none') +
    theme(panel.grid.major.y = element_line(color = 'black')) +
    theme(panel.grid.major.x = element_blank()) +
    theme(text = element_text(size = 10, color = 'black')) +
    theme(axis.text = element_text(color = 'black')) +
    labs(title = var)
})

plots3 <- lapply(unique(branches_summary_long_3$variable), function(var) {
  ggplot(data = branches_summary_long[branches_summary_long$variable == var,], 
         aes(x = site, y = value, fill = site)) +
    stat_summary(fun = "mean", size = 1, geom = "bar") +
    facet_wrap(~year, ncol = 2, scales = "free_x") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
    scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
    theme(legend.title = element_blank()) +
    theme(legend.position = 'none') +
    theme(panel.grid.major.y = element_line(color = 'black')) +
    theme(panel.grid.major.x = element_blank()) +
    theme(text = element_text(size = 10, color = 'black')) +
    theme(axis.text = element_text(color = 'black')) +
    labs(title = var)
})

plots4 <- lapply(unique(branches_summary_long_4$variable), function(var) {
  ggplot(data = branches_summary_long[branches_summary_long$variable == var,], 
         aes(x = site, y = value, fill = site)) +
    stat_summary(fun = "mean", size = 1, geom = "bar") +
    facet_wrap(~year, ncol = 2, scales = "free_x") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5, size = rel(1.5))) +
    scale_fill_manual(values = c("coral1","burlywood2","palegreen4")) +
    theme(legend.title = element_blank()) +
    theme(legend.position = 'none') +
    theme(panel.grid.major.y = element_line(color = 'black')) +
    theme(panel.grid.major.x = element_blank()) +
    theme(text = element_text(size = 10, color = 'black')) +
    theme(axis.text = element_text(color = 'black')) +
    labs(title = var)
})

# Organizar los gráficos en una figura
gs_1 <- ggarrange(plotlist = plots1, ncol = 1, nrow = 4)
gs_2 <- ggarrange(plotlist = plots2, ncol = 1, nrow = 4)
gs_3 <- ggarrange(plotlist = plots3, ncol = 1, nrow = 4)
gs_4 <- ggarrange(plotlist = plots3, ncol = 1, nrow = 4)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

```
