<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Tratamientos de secado</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
  <link rel="icon" type="image/png" href="fruto.jpg"/>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Inicio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">I Introducción</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    II Sitios
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="II_Phenotypes.html">Fenotipos</a>
    </li>
    <li>
      <a href="II_ER_Climate.html">Clima</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">ENTRE RÍOS</li>
    <li class="divider"></li>
    <li>
      <a href="II_ER_SMN.html">MET ER</a>
    </li>
    <li>
      <a href="II_ER_DL.html">DL ER</a>
    </li>
    <li>
      <a href="II_ER_Soil.html">Suelos ER</a>
    </li>
    <li>
      <a href="II_ER_Asociatedspecies.html">Especies asociadas</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">MORENO</li>
    <li class="divider"></li>
    <li>
      <a href="II_M_inta.html">MET M</a>
    </li>
    <li>
      <a href="II_M_Soil.html">Suelos M</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    III Fenología
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="III_Phenology.html">Fenología</a>
    </li>
    <li>
      <a href="III_Yield.html">Rendimiento</a>
    </li>
    <li>
      <a href="III_Polinization.html">Polinización</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    IV Maduración
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mad_resume.html">Tablas resumen</a>
    </li>
    <li>
      <a href="madPhysical.html">Atributos físicos</a>
    </li>
    <li>
      <a href="madAntioxidant.html">Actividad antioxidante</a>
    </li>
    <li>
      <a href="madPhenols.html">Fenoles</a>
    </li>
    <li>
      <a href="madSSyAcidez.html">Sólidos Solubles y Acidez</a>
    </li>
    <li>
      <a href="madAcids.html">Ácidos orgánicos</a>
    </li>
    <li>
      <a href="madCarbohydrates.html">Carbohidratos</a>
    </li>
    <li>
      <a href="madFiber.html">Fibra dietaria</a>
    </li>
    <li>
      <a href="madCations.html">Cationes</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    V Variabilidad
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="V_Weight.html">Peso</a>
    </li>
    <li>
      <a href="V_Diameter.html">Diámetro</a>
    </li>
    <li>
      <a href="V_Seeds.html">Semillas</a>
    </li>
    <li>
      <a href="V_Colorimetry.html">Colorimetría</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="V_phenols.html">Fenoles</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="V_Reproductive.html">Variables reproductivas</a>
    </li>
    <li>
      <a href="V_Branches.html">Eficiencia reproductiva</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="V_Multivariate.html">Multivariado</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    VI Postcosecha
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="VI_Postharvest.html">Postcosecha</a>
    </li>
    <li>
      <a href="VI_climateric2.html">Climacterio 2</a>
    </li>
    <li>
      <a href="VI_climateric3.html">Climacterio 3</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Otros ensayos
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Genetics.html">Extracción de ADN</a>
    </li>
    <li>
      <a href="extraction_methods.html">Extración química</a>
    </li>
    <li>
      <a href="q2022_quimico.html">Variables químicas 2022</a>
    </li>
    <li>
      <a href="secado.html">Secado ER</a>
    </li>
    <li>
      <a href="dry_test.html">Pruebas de Secado</a>
    </li>
    <li>
      <a href="ER_flores.html">Floración ER</a>
    </li>
  </ul>
</li>
<li>
  <a href="publications.html">Publicaciones</a>
</li>
<li>
  <a href="bibliografia.html">Bibliografía</a>
</li>
<li>
  <a href="about.html">Sobre el sitio</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/ipovilonis/ubajay.github.io">
    <span class=" favicon.ico"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Tratamientos de secado</h1>

</div>


<div id="cambios-en-el-peso" class="section level1">
<h1>Cambios en el peso</h1>
<p>Tabla descriptiva</p>
<pre><code>## # A tibble: 14 × 5
## # Groups:   Temperatura [2]
##    Temperatura Hora      n  Mean    sd
##    &lt;fct&gt;       &lt;fct&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 60          0         3 20.4  0.246
##  2 60          1         3 14.0  1.31 
##  3 60          2         3 12.5  1.34 
##  4 60          3         3 10.5  1.56 
##  5 60          4         3  8.48 1.74 
##  6 60          5         3  6.69 1.75 
##  7 60          6         3  4.97 1.59 
##  8 60          7         3  2.52 0.482
##  9 80          0         3 19.7  0.401
## 10 80          1         3 12.7  0.572
## 11 80          2         3  9.37 0.804
## 12 80          3         3  5.61 0.810
## 13 80          4         3  2.88 0.336
## 14 80          5         3  2.08 0.124</code></pre>
<p>Gráfico de medias con desvío estándar
<img src="dry_test_files/figure-html/unnamed-chunk-3-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Gráfico de líneas de tendencia medias y valores puntuales
<img src="dry_test_files/figure-html/unnamed-chunk-4-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Correlación de cada unidad observacional en el tiempo</p>
<pre><code>##      0    1    2    3    4    5
## 0 1.00 0.82 0.92 0.90 0.88 0.86
## 1 0.82 1.00 0.91 0.86 0.83 0.84
## 2 0.92 0.91 1.00 0.99 0.97 0.96
## 3 0.90 0.86 0.99 1.00 0.99 0.98
## 4 0.88 0.83 0.97 0.99 1.00 1.00
## 5 0.86 0.84 0.96 0.98 1.00 1.00</code></pre>
<p>Matriz de covarianzas</p>
<pre><code>##      0    1    2    3     4    5
## 0 0.24 0.46 0.88 1.28  1.40 1.15
## 1 0.46 1.32 2.06 2.86  3.12 2.67
## 2 0.88 2.06 3.88 5.66  6.26 5.23
## 3 1.28 2.86 5.66 8.41  9.40 7.84
## 4 1.40 3.12 6.26 9.40 10.69 8.98
## 5 1.15 2.67 5.23 7.84  8.98 7.61</code></pre>
<p>Modelo marginal. Estructura autoregresiva de orden 1</p>
<pre><code>## gls(model = Peso ~ Hora * Temperatura + basal, data = datospeso2w, 
##     correlation = corAR1(form = ~1 | Repeticion))</code></pre>
<p>Comprobación de supuestos
<img src="dry_test_files/figure-html/unnamed-chunk-11-1.png" width="75%" style="display: block; margin: auto;" /><img src="dry_test_files/figure-html/unnamed-chunk-11-2.png" width="75%" style="display: block; margin: auto;" /><img src="dry_test_files/figure-html/unnamed-chunk-11-3.png" width="75%" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 1, p-value = 0.2</code></pre>
<p>Coeficientes del modelo</p>
<pre><code>##         (Intercept)               Hora2               Hora3               Hora4               Hora5       Temperatura80 
##             -31.997              -1.540              -3.514              -5.533              -7.323               0.299 
##               basal Hora2:Temperatura80 Hora3:Temperatura80 Hora4:Temperatura80 Hora5:Temperatura80 
##               2.255              -1.825              -3.605              -4.321              -3.329</code></pre>
<p>Anova</p>
<pre><code>## Denom. DF: 19 
##                  numDF F-value p-value
## (Intercept)          1    3276  &lt;.0001
## Hora                 4     124  &lt;.0001
## Temperatura          1     120  &lt;.0001
## basal                1      13  0.0018
## Hora:Temperatura     4       5  0.0066</code></pre>
<p>Efectos simples</p>
<pre><code>## $emmeans
## Hora = 1:
##  Temperatura emmean    SE   df lower.CL upper.CL
##  60           13.22 0.558 17.3    12.05    14.40
##  80           13.52 0.558 17.3    12.35    14.70
## 
## Hora = 2:
##  Temperatura emmean    SE   df lower.CL upper.CL
##  60           11.68 0.558 17.3    10.51    12.86
##  80           10.16 0.558 17.3     8.98    11.33
## 
## Hora = 3:
##  Temperatura emmean    SE   df lower.CL upper.CL
##  60            9.71 0.558 17.3     8.53    10.88
##  80            6.40 0.558 17.3     5.23     7.58
## 
## Hora = 4:
##  Temperatura emmean    SE   df lower.CL upper.CL
##  60            7.69 0.558 17.3     6.52     8.87
##  80            3.67 0.558 17.3     2.49     4.84
## 
## Hora = 5:
##  Temperatura emmean    SE   df lower.CL upper.CL
##  60            5.90 0.558 17.3     4.73     7.08
##  80            2.87 0.558 17.3     1.69     4.04
## 
## Degrees-of-freedom method: appx-satterthwaite 
## Confidence level used: 0.95 
## 
## $contrasts
## Hora = 1:
##  contrast                      estimate    SE  df t.ratio p.value
##  Temperatura60 - Temperatura80    -0.30 0.877 9.7  -0.340  0.7410
## 
## Hora = 2:
##  contrast                      estimate    SE  df t.ratio p.value
##  Temperatura60 - Temperatura80     1.53 0.877 9.7   1.740  0.1130
## 
## Hora = 3:
##  contrast                      estimate    SE  df t.ratio p.value
##  Temperatura60 - Temperatura80     3.31 0.877 9.7   3.770  0.0040
## 
## Hora = 4:
##  contrast                      estimate    SE  df t.ratio p.value
##  Temperatura60 - Temperatura80     4.02 0.877 9.7   4.590  0.0010
## 
## Hora = 5:
##  contrast                      estimate    SE  df t.ratio p.value
##  Temperatura60 - Temperatura80     3.03 0.877 9.7   3.460  0.0060
## 
## Degrees-of-freedom method: appx-satterthwaite</code></pre>
<p>Gráfico de comparaciones
<img src="dry_test_files/figure-html/unnamed-chunk-15-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Modelo
<img src="dry_test_files/figure-html/unnamed-chunk-18-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="actividad-antioxidante" class="section level1">
<h1>Actividad antioxidante</h1>
<p><img src="dry_test_files/figure-html/unnamed-chunk-22-1.png" width="75%" style="display: block; margin: auto;" /><img src="dry_test_files/figure-html/unnamed-chunk-22-2.png" width="75%" style="display: block; margin: auto;" /></p>
<div id="ubajay" class="section level2">
<h2>Ubajay</h2>
<p>Modelo</p>
<pre><code>## Formula:          aao/100 ~ Tratamiento + (1 | Concentracion)
## Data: datosaao_uba
##      AIC      BIC   logLik df.resid 
##    -63.2    -53.7     37.6       30 
## Random-effects (co)variances:
## 
## Conditional model:
##  Groups        Name        Std.Dev.
##  Concentracion (Intercept) 0.592   
## 
## Number of obs: 36 / Conditional model: Concentracion, 3
## 
## Dispersion parameter for beta family (): 26.8 
## 
## Fixed Effects:
## 
## Conditional model:
##            (Intercept)  TratamientoLiofilizado          TratamientoT60          TratamientoT80  
##                 -0.532                  -0.611                  -1.233                  -0.674</code></pre>
<p>Verificación de supuestos
<img src="dry_test_files/figure-html/unnamed-chunk-25-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Anova</p>
<pre><code>## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: aao/100
##             Chisq Df Pr(&gt;Chisq)    
## Tratamiento  32.9  3    3.5e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Comparaciones a posteriori</p>
<pre><code>## $emmeans
##  Tratamiento response     SE  df asymp.LCL asymp.UCL
##  Frizado        0.370 0.0856 Inf    0.2225     0.547
##  Liofilizado    0.242 0.0683 Inf    0.1333     0.398
##  T60            0.146 0.0480 Inf    0.0746     0.267
##  T80            0.230 0.0662 Inf    0.1259     0.384
## 
## Confidence level used: 0.95 
## Intervals are back-transformed from the logit scale 
## 
## $contrasts
##  contrast              odds.ratio    SE  df null z.ratio p.value
##  Frizado / Liofilizado       1.84 0.367 Inf    1   3.070  0.0120
##  Frizado / T60               3.43 0.756 Inf    1   5.600  &lt;.0001
##  Frizado / T80               1.96 0.394 Inf    1   3.360  0.0040
##  Liofilizado / T60           1.86 0.422 Inf    1   2.750  0.0310
##  Liofilizado / T80           1.07 0.223 Inf    1   0.310  0.9900
##  T60 / T80                   0.57 0.130 Inf    1  -2.450  0.0680
## 
## P value adjustment: tukey method for comparing a family of 4 estimates 
## Tests are performed on the log odds ratio scale</code></pre>
<p><img src="dry_test_files/figure-html/unnamed-chunk-27-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="calafate" class="section level2">
<h2>Calafate</h2>
<p>Modelo</p>
<pre><code>## Formula:          aao/100 ~ Tratamiento + (1 | Concentracion)
## Data: datosaao_cal
##      AIC      BIC   logLik df.resid 
##    -73.7    -64.2     42.9       30 
## Random-effects (co)variances:
## 
## Conditional model:
##  Groups        Name        Std.Dev.
##  Concentracion (Intercept) 1.32    
## 
## Number of obs: 36 / Conditional model: Concentracion, 3
## 
## Dispersion parameter for beta family (): 13.1 
## 
## Fixed Effects:
## 
## Conditional model:
##            (Intercept)  TratamientoLiofilizado          TratamientoT60          TratamientoT80  
##                1.73332                -0.00248                -1.30122                -0.79498</code></pre>
<p>Verificación de supuestos
<img src="dry_test_files/figure-html/unnamed-chunk-30-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Anova</p>
<pre><code>## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: aao/100
##             Chisq Df Pr(&gt;Chisq)    
## Tratamiento  24.8  3    1.7e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Comparaciones a posteriori</p>
<pre><code>## $emmeans
##  Tratamiento response    SE  df asymp.LCL asymp.UCL
##  Frizado        0.850 0.101 Inf     0.545     0.964
##  Liofilizado    0.850 0.101 Inf     0.546     0.964
##  T60            0.606 0.190 Inf     0.245     0.880
##  T80            0.719 0.160 Inf     0.352     0.923
## 
## Confidence level used: 0.95 
## Intervals are back-transformed from the logit scale 
## 
## $contrasts
##  contrast              odds.ratio    SE  df null z.ratio p.value
##  Frizado / Liofilizado       1.00 0.297 Inf    1   0.010  1.0000
##  Frizado / T60               3.67 1.161 Inf    1   4.120  &lt;.0001
##  Frizado / T80               2.21 0.659 Inf    1   2.670  0.0380
##  Liofilizado / T60           3.66 1.145 Inf    1   4.160  &lt;.0001
##  Liofilizado / T80           2.21 0.650 Inf    1   2.690  0.0360
##  T60 / T80                   0.60 0.188 Inf    1  -1.630  0.3630
## 
## P value adjustment: tukey method for comparing a family of 4 estimates 
## Tests are performed on the log odds ratio scale</code></pre>
<p><img src="dry_test_files/figure-html/unnamed-chunk-32-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="carotenoides" class="section level1">
<h1>Carotenoides</h1>
<p><img src="dry_test_files/figure-html/unnamed-chunk-35-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## 
## Call:  glm(formula = b_car ~ Tratamiento, family = &quot;Gamma&quot;, data = secado_carotenoides)
## 
## Coefficients:
##            (Intercept)  TratamientoLiofilizado          TratamientoT60          TratamientoT80  
##                0.00437                 0.00351                 0.02042                 0.01069  
## 
## Degrees of Freedom: 11 Total (i.e. Null);  8 Residual
## Null Deviance:       5.57 
## Residual Deviance: 0.579     AIC: 116</code></pre>
<p>Comprobación de supuestos
<img src="dry_test_files/figure-html/unnamed-chunk-37-1.png" width="75%" style="display: block; margin: auto;" /><img src="dry_test_files/figure-html/unnamed-chunk-37-2.png" width="75%" style="display: block; margin: auto;" /><img src="dry_test_files/figure-html/unnamed-chunk-37-3.png" width="75%" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.9, p-value = 0.5</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  3    1.78   0.23
##        8</code></pre>
<p>Anova del modelo</p>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: b_car
##             LR Chisq Df Pr(&gt;Chisq)    
## Tratamiento     75.3  3    3.1e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Comparaciones a posteriori</p>
<pre><code>## $emmeans
##  Tratamiento response   SE df lower.CL upper.CL
##  Frizado        228.6 34.0  8    170.3      348
##  Liofilizado    126.8 18.8  8     94.4      193
##  T60             40.3  6.0  8     30.0       61
##  T80             66.4  9.9  8     49.4      101
## 
## Confidence level used: 0.95 
## Intervals are back-transformed from the inverse scale 
## 
## $contrasts
##  contrast              estimate      SE df t.ratio p.value
##  Frizado - Liofilizado -0.00351 0.00134  8  -2.620  0.1132
##  Frizado - T60         -0.02042 0.00374  8  -5.460  0.0027
##  Frizado - T80         -0.01069 0.00233  8  -4.590  0.0077
##  Liofilizado - T60     -0.01690 0.00386  8  -4.370  0.0102
##  Liofilizado - T80     -0.00718 0.00253  8  -2.840  0.0831
##  T60 - T80              0.00973 0.00431  8   2.260  0.1878
## 
## Note: contrasts are still on the inverse scale 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="dry_test_files/figure-html/unnamed-chunk-39-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="antocianinas" class="section level1">
<h1>Antocianinas</h1>
<p><img src="dry_test_files/figure-html/unnamed-chunk-42-1.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## 
## Call:
## lm(formula = Antocianinas ~ Tratamiento, data = datosanto)
## 
## Coefficients:
##            (Intercept)  TratamientoLiofilizado          TratamientoT60          TratamientoT80  
##                 1306.3                   535.4                  -125.7                   -63.7</code></pre>
<p>Verificación de supuestos
<img src="dry_test_files/figure-html/unnamed-chunk-45-1.png" width="75%" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.9, p-value = 0.1</code></pre>
<p>Anova</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Antocianinas
##             Df  Sum Sq Mean Sq F value Pr(&gt;F)
## Tratamiento  3  829717  276572    1.78   0.23
## Residuals    8 1242103  155263</code></pre>
<p>Comparaciones a posteriori</p>
<pre><code>## $emmeans
##  Tratamiento emmean  SE df lower.CL upper.CL
##  Frizado       1306 228  8      782     1831
##  Liofilizado   1842 228  8     1317     2366
##  T60           1181 228  8      656     1705
##  T80           1243 228  8      718     1767
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast              estimate  SE df t.ratio p.value
##  Frizado - Liofilizado     -535 322  8  -1.664  0.3990
##  Frizado - T60              126 322  8   0.391  0.9780
##  Frizado - T80               64 322  8   0.198  0.9970
##  Liofilizado - T60          661 322  8   2.055  0.2460
##  Liofilizado - T80          599 322  8   1.862  0.3150
##  T60 - T80                  -62 322  8  -0.192  0.9970
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="dry_test_files/figure-html/unnamed-chunk-47-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="correlaciones" class="section level1">
<h1>Correlaciones</h1>
<div id="ubajay-1" class="section level2">
<h2>Ubajay</h2>
<p>Modelo</p>
<pre><code>## Linear mixed model fit by REML [&#39;lmerModLmerTest&#39;]
## Formula: aao ~ (b_car) + (1 | Tratamiento)
##    Data: correlaciones_uba
## REML criterion at convergence: 94.8
## Random effects:
##  Groups      Name        Std.Dev.
##  Tratamiento (Intercept)  0.0    
##  Residual                13.9    
## Number of obs: 12, groups:  Tratamiento, 4
## Fixed Effects:
## (Intercept)        b_car  
##      26.739        0.124  
## optimizer (nloptwrap) convergence code: 0 (OK) ; 0 optimizer warnings; 1 lme4 warnings</code></pre>
<p>Verificación de supuestos
<img src="dry_test_files/figure-html/unnamed-chunk-51-1.png" width="75%" style="display: block; margin: auto;" /><img src="dry_test_files/figure-html/unnamed-chunk-51-2.png" width="75%" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.9, p-value = 0.1</code></pre>
<p>Anova</p>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: aao ~ (b_car) + (1 | Tratamiento)
##    Data: correlaciones_uba
## 
## REML criterion at convergence: 94.8
## 
## Scaled residuals: 
##    Min     1Q Median     3Q    Max 
## -0.981 -0.833 -0.192  0.631  2.102 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  Tratamiento (Intercept)   0       0.0    
##  Residual                194      13.9    
## Number of obs: 12, groups:  Tratamiento, 4
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)   
## (Intercept)  26.7385     7.0651 10.0000    3.78   0.0036 **
## b_car         0.1243     0.0503 10.0000    2.47   0.0330 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##       (Intr)
## b_car -0.822
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<pre><code>## [1] 0.616</code></pre>
<p>Existe evidencia para aceptar que beta1 difiere de cero (R = 0.616,
valor p = 0.033)</p>
<p>Gráfico del modelo ajustado</p>
<p><img src="dry_test_files/figure-html/unnamed-chunk-53-1.png" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="calafate-1" class="section level2">
<h2>Calafate</h2>
<p>Modelo</p>
<pre><code>## Linear mixed model fit by REML [&#39;lmerModLmerTest&#39;]
## Formula: aao ~ (Antocianinas) + (1 | Tratamiento)
##    Data: correlaciones_cal
## REML criterion at convergence: 100
## Random effects:
##  Groups      Name        Std.Dev.
##  Tratamiento (Intercept) 14.4    
##  Residual                12.4    
## Number of obs: 12, groups:  Tratamiento, 4
## Fixed Effects:
##  (Intercept)  Antocianinas  
##     62.37663       0.00641</code></pre>
<p>Verificación de supuestos
<img src="dry_test_files/figure-html/unnamed-chunk-56-1.png" width="110%" style="display: block; margin: auto;" /><img src="dry_test_files/figure-html/unnamed-chunk-56-2.png" width="110%" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.9, p-value = 0.2</code></pre>
<p>Anova</p>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: aao ~ (Antocianinas) + (1 | Tratamiento)
##    Data: correlaciones_cal
## 
## REML criterion at convergence: 100
## 
## Scaled residuals: 
##    Min     1Q Median     3Q    Max 
## -0.987 -0.624 -0.138  0.578  1.328 
## 
## Random effects:
##  Groups      Name        Variance Std.Dev.
##  Tratamiento (Intercept) 207      14.4    
##  Residual                154      12.4    
## Number of obs: 12, groups:  Tratamiento, 4
## 
## Fixed effects:
##              Estimate Std. Error       df t value Pr(&gt;|t|)   
## (Intercept)  62.37663   16.62944  9.93593    3.75   0.0038 **
## Antocianinas  0.00641    0.01046  8.64955    0.61   0.5557   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr)
## Antocianins -0.876</code></pre>
<pre><code>## [1] 0.406</code></pre>
<p>No existe evidencia para aceptar que beta1 difiere de cero (R =
0.406, valor p = 0.029)</p>
<p>Gráfico del modelo ajustado</p>
<p><img src="dry_test_files/figure-html/unnamed-chunk-58-1.png" width="110%" style="display: block; margin: auto;" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
