---
title: "Ensayo 6"
output:
 html_document:
   toc: true
   toc_depth: 5
   toc_float:
     collapsed: false
     smooth_scroll: true
---

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

#Carga de datos
library(readxl)
ensayo6 <- read_excel("database.xlsx", sheet = "Ensayo 6")
ensayo6$dia <- as.factor(ensayo6$Día)
ensayo6$respiracion <- ensayo6$Respiración
ensayo6$Tratamiento <- factor(ensayo6$Tratamiento, levels = c("Control", "Etileno", "1MCP"), labels = c("Control", "Etileno", "1MCP"))

print(ensayo6)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

#Gráficos de interacción
library(ggplot2)
library(dplyr)

# Resumir los datos para el gráfico de interacción
interaction_data <- ensayo6 %>%
  dplyr::group_by(Tratamiento, dia) %>%
  dplyr::summarise(mean_respiracion = mean(respiracion , na.rm = TRUE))

colores<-c("yellow","orange","#285114")
# Crear el gráfico de interacción
gg_interac6 <- ggplot(interaction_data, aes(x = dia, y = mean_respiracion, color = Tratamiento, group = Tratamiento)) +
  geom_line(size=2) +
  geom_point(size=6) +
  labs(title = "Día * Tratamiento",
       x = "Día",
       y = expression("mg " ~ CO[2] ~ "/ Kg.h")) +
  scale_color_manual(values =colores) +
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = rel(0.5))) +
  scale_fill_manual(values = colores) +
  theme(legend.title=element_blank())+
  theme(legend.position='bottom')+
  theme(panel.grid.major.y = element_line(color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=50, color='black'))+
  theme(axis.text = element_text(color='black'))+
  # scale_x_continuous(breaks = c(1, 3, 5, 7))+
  scale_y_continuous(breaks = seq(0,210, 40), limits = c(0, 210))

gg_interac6

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

ensayo6$dia <- as.factor(ensayo6$dia)

model_resp6_full <- lm(respiracion ~ Tratamiento * dia, data = ensayo6)

model_resp6_ident <- gls(respiracion ~ Tratamiento * dia, weights=varIdent(form=~1|dia), data=ensayo6)

model_resp6_ident_ML <- gls(respiracion ~ Tratamiento * dia, weights=varIdent(form=~1|dia), data=ensayo6, method="ML")

model_resp6_varpower_f <- gls(respiracion ~ Tratamiento * dia, weights=varPower(), data=ensayo6)

model_resp6_varexp_f <- gls(respiracion ~ Tratamiento * dia, weights=varExp(), data=ensayo6)

model_resp6_full_log <- lm(log(respiracion) ~ Tratamiento * dia, data = ensayo6)

model_resp6_ident_log <- gls(log(respiracion) ~ Tratamiento * dia, weights=varIdent(form=~1|dia), data=ensayo6)

model_resp6_ident_ML_log <- gls(log(respiracion) ~ Tratamiento * dia, weights=varIdent(form=~1|dia), data=ensayo6, method="ML")

model_resp6_varpower_f_log <- gls(log(respiracion) ~ Tratamiento * dia, weights=varPower(), data=ensayo6)

model_resp6_varexp_f_log <- gls(log(respiracion) ~ Tratamiento * dia, weights=varExp(), data=ensayo6)

library(dplyr)
# Calcular varianzas por nivel de dia
varianza_por_dia <- ensayo6 %>%
  dplyr::group_by(dia) %>%
  dplyr::summarise(var_resp = var(respiracion, na.rm = TRUE))

# Unir las varianzas al conjunto de datos original
ensayo6 <- ensayo6 %>%
  dplyr::left_join(varianza_por_dia, by = "dia")

# # Limpiar ensayo6: seleccionar columnas únicas y renombrar para claridad
# ensayo6_clean <- ensayo6 %>%
#   dplyr::select(Día, Tratamiento, respiracion, dia, var_resp.x) %>%
#   dplyr::rename(var_resp = var_resp.x) # Usamos var_resp.x como la columna de varianza
# 
# # Modelo full con interacción y pesos
# model_full_weighted <- lm(respiracion ~ Tratamiento * dia, 
#                           data = ensayo6_clean, 
#                           weights = 1 / var_resp) # Usamos la columna var_resp de ensayo6
# 
# model_full_weighted_log <- lm(log(respiracion) ~ Tratamiento * dia, 
#                           data = ensayo6_clean, 
#                           weights = 1 / var_resp)

ensayo6$dia <- as.numeric(ensayo6$dia)

model_resp6_varpower <- gls(respiracion ~ Tratamiento * dia, weights=varPower(form = ~ dia), data=ensayo6)

model_resp6_varexp <- gls(respiracion ~ Tratamiento * dia, weights=varExp(form = ~ dia), data=ensayo6)

model_resp6_varpower_log <- gls(log(respiracion) ~ Tratamiento * dia, weights=varPower(form = ~ dia), data=ensayo6)

model_resp6_varexp_log <- gls(log(respiracion) ~ Tratamiento * dia, weights=varExp(form = ~ dia), data=ensayo6)

# Ajustar un modelo GLM con distribución Gamma
gamma_model <- glm(respiracion ~ Tratamiento * dia, 
                   data = ensayo6, 
                   family = Gamma(link = "log"))

# Calcular AIC para comparación
comp_mod <- AIC(model_resp6_full, model_resp6_ident, model_resp6_ident_ML, model_resp6_varpower_f, model_resp6_varpower, model_resp6_varexp_f, model_resp6_varexp,
    model_resp6_full_log, model_resp6_ident_log, model_resp6_ident_ML_log, model_resp6_varpower_f_log, model_resp6_varpower_log, model_resp6_varexp_f_log, model_resp6_varexp_log, gamma_model)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

# 1. Gráfico de Residuos vs Predichos
residuos <- residuals(model_resp6_ident_ML_log)       # Residuos del modelo
predichos <- fitted(model_resp6_ident_ML_log)         # Valores predichos

grafico_res_pred <- ggplot(data = NULL, aes(x = predichos, y = residuos)) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Residuos vs Predichos",
       x = "Valores Predichos",
       y = "Residuos") +
  theme_classic() +
  theme(text = element_text(size = 12))

print(grafico_res_pred)

# 2. QQ-plot
grafico_qq <- ggplot(data = data.frame(residuos), aes(sample = residuos)) +
  stat_qq() +
  stat_qq_line(color = "red", linetype = "dashed") +
  labs(title = "QQ-Plot de Residuos",
       x = "Cuantiles Teóricos",
       y = "Cuantiles de Residuos") +
  theme_classic() +
  theme(text = element_text(size = 12))

print(grafico_qq)

# 3. Prueba de Levene (homogeneidad de varianzas)
ensayo6$dia <- as.factor(ensayo6$dia)
library(car)
levene_test <- leveneTest(log(respiracion) ~ dia, data = ensayo6)
print(levene_test)

# 4. Prueba de Shapiro-Wilk (normalidad de residuos)
shapiro_test <- shapiro.test(residuos)
print(shapiro_test)

# # 5. Identificación de outliers (opcional, ver recomendaciones abajo)
# # Calcular residuos estandarizados
# residuos_std <- rstandard(model_resp6_ident)
# 
# # Mostrar observaciones con residuos estandarizados > 2 o < -2 (posibles outliers)
# outliers <- which(abs(residuos_std) > 2)
# if(length(outliers) > 0) {
#   print("Posibles outliers (índices de las observaciones):")
#   print(outliers)
#   print("Detalles de las observaciones:")
#   print(ensayo6[outliers, ])
# } else {
#   print("No se detectaron outliers con |residuos estandarizados| > 2")
# }

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

# anova(model_resp6_ident_ML_log)

library(car)
Anova(model_resp6_ident_ML_log)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(emmeans)
comp_resp6<-emmeans(model_resp6_ident_ML_log, pairwise ~ Tratamiento|dia)
comp_resp6
plot(comp_resp6, comparisons = TRUE, 
     xlab = expression(log("mg CO"[2] * "/Kg.h")), 
     ylab = "")

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

# Asegúrate de que interaction_data_with_sd tenga los datos necesarios
# Si sd_model.x está NA, necesitamos recalcular los errores estándar del modelo

# Usar emmeans para obtener predicciones y errores estándar en la escala logarítmica
library(emmeans)

# Obtener las medias estimadas y sus errores estándar en la escala logarítmica
means_emm <- emmeans(model_resp6_ident_ML_log, ~ Tratamiento | dia)

# Convertir a dataframe
means_data <- as.data.frame(summary(means_emm))

# Renombrar columnas
names(means_data)[names(means_data) == "emmean"] <- "mean_respiracion_log"
names(means_data)[names(means_data) == "SE"] <- "sd_model_log"

# Transformar las medias a la escala de la respuesta
means_data$mean_respiracion <- exp(means_data$mean_respiracion_log)

# Transformar los errores estándar a la escala de la respuesta
# Para un modelo logarítmico, el error estándar en la escala original se calcula aproximadamente como:
# sd_response ≈ mean_respiracion * sd_model_log
means_data$sd_model_response <- means_data$mean_respiracion * means_data$sd_model_log

# Seleccionar solo las columnas relevantes
means_data_final <- means_data[, c("Tratamiento", "dia", "mean_respiracion", "sd_model_response")]

# Unir con interaction_data
interaction_data_with_sd <- left_join(interaction_data, 
                                     means_data_final, 
                                     by = c("dia", "Tratamiento"))

# Asegurarnos de que los niveles de los factores coincidan
interaction_data_with_sd$Tratamiento <- factor(interaction_data_with_sd$Tratamiento, levels = c("Control", "Etileno", "1MCP"), labels = c("Control", "Etileno", "1MCP"))
interaction_data_with_sd$dia <- factor(interaction_data_with_sd$dia, levels = c("1", "3", "5", "7"))

# Mostrar el resultado
print(interaction_data_with_sd)

```

```{r  , echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

colores<-c("yellow","orange","#285114")

library(ggplot2)
gg_resp_TD <- ggplot(interaction_data_with_sd, aes(x = dia, y = mean_respiracion.x, fill = Tratamiento, group = Tratamiento)) +
  stat_summary(fun = "mean", size = 0.05, geom = "bar", position=position_dodge(0.3), width = .3) +
  geom_errorbar(aes(ymin=mean_respiracion.x-sd_model_response, ymax=mean_respiracion.x+sd_model_response),
                width=.1, position=position_dodge(0.3))+
  labs(x="", y= expression("mg " ~ CO[2] ~ "/ Kg.h"))+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5, size = rel(0.5))) +
  scale_fill_manual(values = colores) +
  theme(legend.title=element_blank())+
  theme(legend.position='bottom')+
  theme(panel.grid.major.y = element_line(color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=40, color='black'))+
  theme(axis.text = element_text(color='black'))+
  scale_y_continuous(breaks = seq(0,210, 40), limits = c(0, 210))+
  annotate("text", x = 1+0.1, y = interaction_data_with_sd$mean_respiracion.x[1] + interaction_data_with_sd$sd_model_response[1] + 7, label = "a", size = 8) +
  annotate("text", x = 2+0.1, y = interaction_data_with_sd$mean_respiracion.x[2] + interaction_data_with_sd$sd_model_response[2] + 7, label = "a", size = 8) +
  annotate("text", x = 3+0.1, y = interaction_data_with_sd$mean_respiracion.x[3] + interaction_data_with_sd$sd_model_response[3] + 7, label = "a", size = 8) +
  annotate("text", x = 4+0.1, y = interaction_data_with_sd$mean_respiracion.x[4] + interaction_data_with_sd$sd_model_response[4] + 7, label = "b", size = 8) +
  annotate("text", x = 1-0.1, y = interaction_data_with_sd$mean_respiracion.x[5] + interaction_data_with_sd$sd_model_response[5] + 7, label = "a", size = 8) +
  annotate("text", x = 2-0.1, y = interaction_data_with_sd$mean_respiracion.x[6] + interaction_data_with_sd$sd_model_response[6] + 7, label = "a", size = 8) +
  annotate("text", x = 3-0.1, y = interaction_data_with_sd$mean_respiracion.x[7] + interaction_data_with_sd$sd_model_response[7] + 7, label = "a", size = 8) +
  annotate("text", x = 4-0.1, y = interaction_data_with_sd$mean_respiracion.x[8] + interaction_data_with_sd$sd_model_response[8] + 7, label = "a", size = 8) +
  annotate("text", x = 1, y = interaction_data_with_sd$mean_respiracion.x[9] + interaction_data_with_sd$sd_model_response[9] + 7, label = "b", size = 8) +
  annotate("text", x = 2, y = interaction_data_with_sd$mean_respiracion.x[10] + interaction_data_with_sd$sd_model_response[10] + 7, label = "a", size = 8) +
  annotate("text", x = 3, y = interaction_data_with_sd$mean_respiracion.x[11] + interaction_data_with_sd$sd_model_response[11] + 7, label = "b", size = 8) +
  annotate("text", x = 4, y = interaction_data_with_sd$mean_respiracion.x[12] + interaction_data_with_sd$sd_model_response[12] + 7, label = "ab", size = 8)

gg_resp_TD

# ggsave("gg_resp_TD.tiff", plot = gg_resp_TD, device = "tiff", width = 15, height = 8, units = "in", dpi = 300)

```
