<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Ensayo 8</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
  <link rel="icon" type="image/png" href="fruto.jpg"/>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Inicio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">I Introducción</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    II Sitios
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="II_Phenotypes2.html">Fenotipos</a>
    </li>
    <li>
      <a href="II_maps1.html">Mapas</a>
    </li>
    <li>
      <a href="II_ER_Climate.html">Clima</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">ENTRE RÍOS</li>
    <li class="divider"></li>
    <li>
      <a href="II_ER_SMN.html">MET ER</a>
    </li>
    <li>
      <a href="II_ER_DL.html">DL ER</a>
    </li>
    <li>
      <a href="II_ER_Soil.html">Suelos ER</a>
    </li>
    <li>
      <a href="II_ER_Asociatedspecies.html">Especies asociadas</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">MORENO</li>
    <li class="divider"></li>
    <li>
      <a href="II_M_inta.html">MET M</a>
    </li>
    <li>
      <a href="II_M_Soil.html">Suelos M</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    III Fenología
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="III_Flowers.html">Fenología</a>
    </li>
    <li>
      <a href="III_Yield.html">Rendimiento</a>
    </li>
    <li>
      <a href="III_Polinization.html">Polinización</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    IV Maduración
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mad_resume.html">Tablas resumen</a>
    </li>
    <li>
      <a href="madPhysical.html">Atributos físicos</a>
    </li>
    <li>
      <a href="madAntioxidant.html">Actividad antioxidante</a>
    </li>
    <li>
      <a href="madPhenols.html">Fenoles</a>
    </li>
    <li>
      <a href="madSSyAcidez.html">Sólidos Solubles y Acidez</a>
    </li>
    <li>
      <a href="madAcids.html">Ácidos orgánicos</a>
    </li>
    <li>
      <a href="madCarbohydrates.html">Carbohidratos</a>
    </li>
    <li>
      <a href="madFiber.html">Fibra dietaria</a>
    </li>
    <li>
      <a href="madCations.html">Cationes</a>
    </li>
    <li>
      <a href="mad_PCA.html">Multivariado</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    V Postcosecha
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Ensayo1.html">Ensayo 1</a>
    </li>
    <li>
      <a href="Ensayo2.html">Ensayo 2</a>
    </li>
    <li>
      <a href="Ensayo3.html">Ensayo 3</a>
    </li>
    <li>
      <a href="Ensayo4.html">Ensayo 4</a>
    </li>
    <li>
      <a href="Ensayo5.html">Ensayo 5</a>
    </li>
    <li>
      <a href="Ensayo6.html">Ensayo 6</a>
    </li>
    <li>
      <a href="Ensayo7.html">Ensayo 7</a>
    </li>
    <li>
      <a href="Ensayo8.html">Ensayo 8</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    VI Variabilidad
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="V_Colorimetry.html">Colorimetría</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="V_flowers.html">Variables reproductivas</a>
    </li>
    <li>
      <a href="V_Branches.html">Eficiencia reproductiva</a>
    </li>
    <li>
      <a href="V_fruits.html">Frutos</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="V_correlations.html">Correlaciones</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Otros ensayos
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Genetics.html">Extracción de ADN</a>
    </li>
    <li>
      <a href="extraction_methods.html">Extracción química</a>
    </li>
    <li>
      <a href="q2022_quimico.html">Variables químicas 2022</a>
    </li>
    <li>
      <a href="secado.html">Secado ER</a>
    </li>
    <li>
      <a href="dry_test.html">Pruebas de Secado</a>
    </li>
    <li>
      <a href="calafate.html">Calafate</a>
    </li>
    <li>
      <a href="microprop.html">Micropropagación</a>
    </li>
  </ul>
</li>
<li>
  <a href="publications.html">Publicaciones</a>
</li>
<li>
  <a href="bibliografia.html">Bibliografía</a>
</li>
<li>
  <a href="about.html">Sobre el sitio</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/ipovilonis/ubajay.github.io">
    <span class=" favicon.ico"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Ensayo 8</h1>

</div>


<div id="conservación-a-1c" class="section level1">
<h1>Conservación a 1°C</h1>
<div id="respiración" class="section level2">
<h2>Respiración</h2>
<p>Tabla resumen</p>
<pre><code>## # A tibble: 4 × 4
##   Día       n Mean_resp sd_resp
##   &lt;fct&gt; &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 1         3     28.0     6.01
## 2 5         3      8.58    4.12
## 3 7         3     23.8     4.94
## 4 10        2     23.0     1.64</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-3-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = respiracion ~ Día, data = data_resp)</code></pre>
<p>Análisis de regresión</p>
<pre><code>## Analysis of Variance Table
## 
## Response: respiracion
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## Día        3 641.71 213.905  9.4964 0.007299 **
## Residuals  7 157.67  22.525                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## $emmeans
##  Día    emmean       SE df  lower.CL upper.CL
##  1   28.049379 2.740120  7 21.570024 34.52873
##  5    8.578073 2.740120  7  2.098718 15.05743
##  7   23.774397 2.740120  7 17.295041 30.25375
##  10  22.993329 3.355948  7 15.057772 30.92889
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast       estimate       SE df t.ratio p.value
##  Día1 - Día5   19.471306 3.875115  7   5.025  0.0064
##  Día1 - Día7    4.274983 3.875115  7   1.103  0.6991
##  Día1 - Día10   5.056050 4.332511  7   1.167  0.6640
##  Día5 - Día7  -15.196323 3.875115  7  -3.922  0.0231
##  Día5 - Día10 -14.415256 4.332511  7  -3.327  0.0489
##  Día7 - Día10   0.781067 4.332511  7   0.180  0.9977
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-8-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="firmeza" class="section level2">
<h2>Firmeza</h2>
<p>Tabla resumen</p>
<pre><code>## # A tibble: 4 × 4
##   Día       n Mean_firmeza sd_firmeza
##   &lt;fct&gt; &lt;int&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 1        22         1.41      0.540
## 2 5        22         1.05      0.505
## 3 7        22         1.13      0.412
## 4 10       22         1.13      0.322</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-11-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = Firmeza ~ Día, data = data_fisico)</code></pre>
<p>Análisis de la varianza</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Firmeza
##           Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
## Día        3  1.6232 0.54106  2.6393 0.05477 .
## Residuals 84 17.2200 0.20500                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## $emmeans
##  Día   emmean         SE df  lower.CL upper.CL
##  1   1.409091 0.09653073 84 1.2171290 1.601053
##  5   1.054545 0.09653073 84 0.8625835 1.246507
##  7   1.127273 0.09653073 84 0.9353108 1.319235
##  10  1.127273 0.09653073 84 0.9353108 1.319235
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast       estimate        SE df t.ratio p.value
##  Día1 - Día5   0.3545455 0.1365151 84   2.597  0.0531
##  Día1 - Día7   0.2818182 0.1365151 84   2.064  0.1733
##  Día1 - Día10  0.2818182 0.1365151 84   2.064  0.1733
##  Día5 - Día7  -0.0727273 0.1365151 84  -0.533  0.9509
##  Día5 - Día10 -0.0727273 0.1365151 84  -0.533  0.9509
##  Día7 - Día10  0.0000000 0.1365151 84   0.000  1.0000
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-16-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="colorimetría" class="section level2">
<h2>Colorimetría</h2>
<div id="l" class="section level3">
<h3>L*</h3>
<p>Tabla resumen</p>
<pre><code>## # A tibble: 4 × 4
##   Día       n Mean_L_color sd_L_color
##   &lt;fct&gt; &lt;int&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 1        24         60.6       4.50
## 2 5        24         56.1       7.55
## 3 7        24         54.0       6.44
## 4 10       24         53.4       4.76</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-19-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = L_color ~ Día, data = data_fisico)</code></pre>
<p>Análisis de la varianza</p>
<pre><code>## Analysis of Variance Table
## 
## Response: L_color
##           Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Día        3  770.2 256.724  7.2618  2e-04 ***
## Residuals 92 3252.5  35.353                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## $emmeans
##  Día   emmean       SE df lower.CL upper.CL
##  1   60.59625 1.213688 92 58.18576 63.00674
##  5   56.10792 1.213688 92 53.69743 58.51841
##  7   53.97333 1.213688 92 51.56284 56.38382
##  10  53.38333 1.213688 92 50.97284 55.79382
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast     estimate       SE df t.ratio p.value
##  Día1 - Día5  4.488333 1.716414 92   2.615  0.0502
##  Día1 - Día7  6.622917 1.716414 92   3.859  0.0012
##  Día1 - Día10 7.212917 1.716414 92   4.202  0.0004
##  Día5 - Día7  2.134583 1.716414 92   1.244  0.6009
##  Día5 - Día10 2.724583 1.716414 92   1.587  0.3908
##  Día7 - Día10 0.590000 1.716414 92   0.344  0.9859
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-24-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="a" class="section level3">
<h3>a*</h3>
<p>Tabla resumen</p>
<pre><code>## # A tibble: 4 × 4
##   Día       n Mean_a_color sd_a_color
##   &lt;fct&gt; &lt;int&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 1        24         3.70       3.35
## 2 5        24        11.6        4.84
## 3 7        24        12.4        6.55
## 4 10       24        14.6        3.72</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-26-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = a_color ~ Día, data = data_fisico)</code></pre>
<p>Análisis de la varianza</p>
<pre><code>## Analysis of Variance Table
## 
## Response: a_color
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Día        3 1637.0  545.65  23.872 1.629e-11 ***
## Residuals 92 2102.9   22.86                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## $emmeans
##  Día   emmean        SE df  lower.CL  upper.CL
##  1    3.70125 0.9759081 92  1.763012  5.639488
##  5   11.61292 0.9759081 92  9.674679 13.551154
##  7   12.43042 0.9759081 92 10.492179 14.368654
##  10  14.62958 0.9759081 92 12.691346 16.567821
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast       estimate       SE df t.ratio p.value
##  Día1 - Día5   -7.911667 1.380143 92  -5.732  &lt;.0001
##  Día1 - Día7   -8.729167 1.380143 92  -6.325  &lt;.0001
##  Día1 - Día10 -10.928333 1.380143 92  -7.918  &lt;.0001
##  Día5 - Día7   -0.817500 1.380143 92  -0.592  0.9342
##  Día5 - Día10  -3.016667 1.380143 92  -2.186  0.1349
##  Día7 - Día10  -2.199167 1.380143 92  -1.593  0.3874
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-31-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="b" class="section level3">
<h3>b*</h3>
<p>Tabla resumen</p>
<pre><code>## # A tibble: 4 × 4
##   Día       n Mean_b_color sd_b_color
##   &lt;fct&gt; &lt;int&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 1        24         51.3       5.15
## 2 5        24         48.2       9.89
## 3 7        24         47.0      10.0 
## 4 10       24         46.7       8.22</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-33-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = b_color ~ Día, data = data_fisico)</code></pre>
<p>Análisis de la varianza</p>
<pre><code>## Analysis of Variance Table
## 
## Response: b_color
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Día        3  310.4 103.464  1.4158 0.2432
## Residuals 92 6723.2  73.079</code></pre>
<pre><code>## $emmeans
##  Día   emmean       SE df lower.CL upper.CL
##  1   51.27542 1.744978 92 47.80974 54.74109
##  5   48.18417 1.744978 92 44.71849 51.64984
##  7   47.04583 1.744978 92 43.58016 50.51151
##  10  46.72083 1.744978 92 43.25516 50.18651
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast     estimate       SE df t.ratio p.value
##  Día1 - Día5  3.091250 2.467772 92   1.253  0.5952
##  Día1 - Día7  4.229583 2.467772 92   1.714  0.3224
##  Día1 - Día10 4.554583 2.467772 92   1.846  0.2589
##  Día5 - Día7  1.138333 2.467772 92   0.461  0.9672
##  Día5 - Día10 1.463333 2.467772 92   0.593  0.9340
##  Día7 - Día10 0.325000 2.467772 92   0.132  0.9992
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-38-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="actividad-antioxidante" class="section level2">
<h2>Actividad antioxidante</h2>
<p>Tabla resumen</p>
<pre><code>## # A tibble: 9 × 5
## # Groups:   Día [3]
##   Día   Conc      n Mean_aao sd_aao
##   &lt;fct&gt; &lt;fct&gt; &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;
## 1 1     0.125     3    24.2    6.13
## 2 1     0.25      3    34.3   16.3 
## 3 1     0.5       3    59.5   24.4 
## 4 7     0.125     3    11.9    2.79
## 5 7     0.25      3    20.3    5.38
## 6 7     0.5       3    40.8    7.04
## 7 10    0.125     3     8.96   4.13
## 8 10    0.25      3    10.5    3.13
## 9 10    0.5       3    23.4    9.78</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-41-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## Formula:          aao/100 ~ Día + (1 | Conc)
## Data: data_aao
##       AIC       BIC    logLik  df.resid 
## -39.01704 -32.53785  24.50852        22 
## Random-effects (co)variances:
## 
## Conditional model:
##  Groups Name        Std.Dev.
##  Conc   (Intercept) 0.5742  
## 
## Number of obs: 27 / Conditional model: Conc, 3
## 
## Dispersion parameter for beta family (): 20.1 
## 
## Fixed Effects:
## 
## Conditional model:
## (Intercept)         Día7        Día10  
##     -0.4159      -0.7540      -1.3981</code></pre>
<p>Anova</p>
<pre><code>## Analysis of Deviance Table (Type II Wald chisquare tests)
## 
## Response: aao/100
##      Chisq Df Pr(&gt;Chisq)    
## Día 31.692  2  1.313e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Comparaciones a posteriori</p>
<pre><code>## $emmeans
##  Día  response         SE  df  asymp.LCL asymp.UCL
##  1   0.3974921 0.08728567 Inf 0.24411366 0.5740528
##  7   0.2368605 0.06745631 Inf 0.12994994 0.3920896
##  10  0.1401488 0.04706122 Inf 0.07047125 0.2594869
## 
## Confidence level used: 0.95 
## Intervals are back-transformed from the logit scale 
## 
## $contrasts
##  contrast     odds.ratio        SE  df asymp.LCL asymp.UCL
##  Día1 / Día7    2.125578 0.4830323 Inf  1.247877  3.620615
##  Día1 / Día10   4.047621 1.0261822 Inf  2.234321  7.332535
##  Día7 / Día10   1.904245 0.4968901 Inf  1.033060  3.510107
## 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 3 estimates 
## Intervals are back-transformed from the log odds ratio scale</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-46-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-47-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="fenoles" class="section level2">
<h2>Fenoles</h2>
<pre><code>## # A tibble: 3 × 4
##   Día       n Mean_fenoles sd_fenoles
##   &lt;fct&gt; &lt;int&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 1         3         90.7      11.1 
## 2 7         3         72.3       5.28
## 3 10        3         70.4      14.9</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-50-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = Fenoles ~ Día, data = data)</code></pre>
<p>Análisis de regresión</p>
<pre><code>## 
## Call:
## lm(formula = Fenoles ~ Día, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -10.928  -6.480  -5.037   4.685  19.977 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   98.083      9.897   9.910 2.27e-05 ***
## Día          -10.141      4.581  -2.213   0.0625 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.22 on 7 degrees of freedom
## Multiple R-squared:  0.4117, Adjusted R-squared:  0.3277 
## F-statistic:   4.9 on 1 and 7 DF,  p-value: 0.06247</code></pre>
<p>Por cada día transcurrido los frutos pierden en promedio -2.37 mg eq.
Tán/100g PF (p=0.041)</p>
<p>Análisis de la varianza</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Fenoles
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Día        2 750.90  375.45  3.0129 0.1242
## Residuals  6 747.68  124.61</code></pre>
</div>
<div id="correlación-aao-y-fenoles" class="section level2">
<h2>Correlación AAO y fenoles</h2>
<pre><code>## 
## Call:
## lm(formula = aao ~ Fenoles, data = data3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -18.432  -6.848  -3.266   5.223  19.832 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) -51.9147    27.5612  -1.884    0.102  
## Fenoles       1.1974     0.3495   3.426    0.011 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.53 on 7 degrees of freedom
## Multiple R-squared:  0.6264, Adjusted R-squared:  0.5731 
## F-statistic: 11.74 on 1 and 7 DF,  p-value: 0.01104</code></pre>
<pre><code>## [1] 0.791479</code></pre>
<p>Hay evidencia para aceptar que beta1 difiere de cero (r = 0.791,
valor p = 0.011 )
<img src="Ensayo8_files/figure-html/unnamed-chunk-60-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="carotenoides" class="section level2">
<h2>Carotenoides</h2>
<pre><code>## # A tibble: 3 × 4
##   Día       n Mean_Carotenoides sd_Carotenoides
##   &lt;fct&gt; &lt;int&gt;             &lt;dbl&gt;           &lt;dbl&gt;
## 1 1         6              205.            29.5
## 2 7         6              298.            38.8
## 3 10        6              193.            39.2</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-63-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = Carotenoides ~ Día, data = data)</code></pre>
<p>ANOVA</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Carotenoides
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Día        2  39212 19606.2  15.021 0.0002622 ***
## Residuals 15  19579  1305.3                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Comparaciones a posteriori</p>
<pre><code>## $emmeans
##  Día   emmean      SE df lower.CL upper.CL
##  1   204.8070 14.7494 15 173.3694 236.2447
##  7   297.5998 14.7494 15 266.1622 329.0375
##  10  193.3654 14.7494 15 161.9277 224.8030
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast      estimate       SE df t.ratio p.value
##  Día1 - Día7  -92.79280 20.85881 15  -4.449  0.0013
##  Día1 - Día10  11.44169 20.85881 15   0.549  0.8488
##  Día7 - Día10 104.23449 20.85881 15   4.997  0.0004
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-68-1.png" width="95%" style="display: block; margin: auto;" />
A los 7 días se encontró un aumento significativo en la concentración de
carotenoides (p=0.009 )</p>
</div>
<div id="clorofila-a" class="section level2">
<h2>Clorofila a</h2>
<pre><code>## # A tibble: 3 × 4
##   Día       n Mean_Clorofila_a sd_Clorofila_a
##   &lt;fct&gt; &lt;int&gt;            &lt;dbl&gt;          &lt;dbl&gt;
## 1 1         6            31.4           10.1 
## 2 7         6            24.8            9.70
## 3 10        6             9.91           3.97</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-70-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = Clorofila_a ~ Día, data = data)</code></pre>
<p>ANOVA</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Clorofila_a
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## Día        2 1458.3  729.16  10.359 0.001493 **
## Residuals 15 1055.9   70.39                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Comparaciones a posteriori</p>
<pre><code>## $emmeans
##  Día    emmean       SE df  lower.CL upper.CL
##  1   31.433842 3.425173 15 24.133259 38.73442
##  7   24.810140 3.425173 15 17.509557 32.11072
##  10   9.909989 3.425173 15  2.609406 17.21057
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast      estimate       SE df t.ratio p.value
##  Día1 - Día7   6.623702 4.843926 15   1.367  0.3820
##  Día1 - Día10 21.523853 4.843926 15   4.443  0.0013
##  Día7 - Día10 14.900151 4.843926 15   3.076  0.0198
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-75-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="clorofila-b" class="section level2">
<h2>Clorofila b</h2>
<pre><code>## # A tibble: 3 × 4
##   Día       n Mean_Clorofila_b sd_Clorofila_b
##   &lt;fct&gt; &lt;int&gt;            &lt;dbl&gt;          &lt;dbl&gt;
## 1 1         6             53.9          17.4 
## 2 7         6             42.7          16.5 
## 3 10        6             16.9           6.48</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-77-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = Clorofila_b ~ Día, data = data)</code></pre>
<p>ANOVA</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Clorofila_b
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## Día        2 4318.8 2159.39  10.474 0.001423 **
## Residuals 15 3092.6  206.17                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Comparaciones a posteriori</p>
<pre><code>## $emmeans
##  Día   emmean      SE df lower.CL upper.CL
##  1   53.89372 5.86191 15 41.39935 66.38808
##  7   42.72866 5.86191 15 30.23430 55.22303
##  10  16.90737 5.86191 15  4.41300 29.40173
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast     estimate       SE df t.ratio p.value
##  Día1 - Día7  11.16506 8.289992 15   1.347  0.3924
##  Día1 - Día10 36.98635 8.289992 15   4.462  0.0012
##  Día7 - Día10 25.82130 8.289992 15   3.115  0.0183
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-82-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="correlación-aao-y-carotenoides" class="section level2">
<h2>Correlación AAO y Carotenoides</h2>
<pre><code>## 
## Call:
## lm(formula = aao ~ Carotenoides, data = data3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.031  -7.139  -0.673   6.787  45.988 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  41.54099   24.12452   1.722    0.129
## Carotenoides -0.00135    0.10363  -0.013    0.990
## 
## Residual standard error: 22.13 on 7 degrees of freedom
## Multiple R-squared:  2.423e-05,  Adjusted R-squared:  -0.1428 
## F-statistic: 0.0001696 on 1 and 7 DF,  p-value: 0.99</code></pre>
<pre><code>## [1] -0.004922504</code></pre>
<p>No existe evidencia para aceptar que beta1 difiere de cero (r =
-0.004, valor p = 0.990)
<img src="Ensayo8_files/figure-html/unnamed-chunk-86-1.png" width="95%" style="display: block; margin: auto;" />
No existe evidencia para aceptar que beta1 difiere de cero (r = 0.082,
valor p = 0.8330)</p>
</div>
<div id="acidez-total-titulable" class="section level2">
<h2>Acidez total titulable</h2>
<pre><code>## # A tibble: 3 × 4
##   Día       n Mean_Acidez sd_Acidez
##   &lt;fct&gt; &lt;int&gt;       &lt;dbl&gt;     &lt;dbl&gt;
## 1 1         3        2.07     0.125
## 2 7         3        1.70     0.132
## 3 10        3        1.58     0.157</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-90-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = Acidez ~ Día, data = data)</code></pre>
<p>Análisis de regresión</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Acidez
##           Df  Sum Sq  Mean Sq F value  Pr(&gt;F)  
## Día        2 0.38603 0.193017  10.013 0.01225 *
## Residuals  6 0.11566 0.019277                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## $emmeans
##  Día   emmean         SE df lower.CL upper.CL
##  1   2.065067 0.08016023  6 1.868922 2.261212
##  7   1.702400 0.08016023  6 1.506255 1.898545
##  10  1.576533 0.08016023  6 1.380388 1.772678
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast      estimate        SE df t.ratio p.value
##  Día1 - Día7  0.3626667 0.1133637  6   3.199  0.0426
##  Día1 - Día10 0.4885333 0.1133637  6   4.309  0.0119
##  Día7 - Día10 0.1258667 0.1133637  6   1.110  0.5428
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-95-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="ph-inicial" class="section level2">
<h2>pH inicial</h2>
<pre><code>## # A tibble: 3 × 4
##   Día       n Mean_pH_inicial sd_pH_inicial
##   &lt;fct&gt; &lt;int&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 1         3            3.30        0.0252
## 2 7         3            3.40        0.0404
## 3 10        3            3.40        0.0289</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-97-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = pH_inicial ~ Día, data = data)</code></pre>
<p>Análisis de regresión</p>
<pre><code>## Analysis of Variance Table
## 
## Response: pH_inicial
##           Df   Sum Sq   Mean Sq F value  Pr(&gt;F)  
## Día        2 0.018756 0.0093778  9.0753 0.01533 *
## Residuals  6 0.006200 0.0010333                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## $emmeans
##  Día   emmean         SE df lower.CL upper.CL
##  1   3.303333 0.01855922  6 3.257921 3.348746
##  7   3.403333 0.01855922  6 3.357921 3.448746
##  10  3.396667 0.01855922  6 3.351254 3.442079
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast        estimate         SE df t.ratio p.value
##  Día1 - Día7  -0.10000000 0.02624669  6  -3.810  0.0207
##  Día1 - Día10 -0.09333333 0.02624669  6  -3.556  0.0278
##  Día7 - Día10  0.00666667 0.02624669  6   0.254  0.9653
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-102-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="ratio" class="section level2">
<h2>Ratio</h2>
<pre><code>## # A tibble: 3 × 4
##   Día       n Mean_Ratio sd_Ratio
##   &lt;fct&gt; &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;
## 1 1         3       4.54   0.511 
## 2 7         3       4.55   0.207 
## 3 10        3       4.27   0.0671</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-104-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = Ratio ~ Día, data = data)</code></pre>
<p>Análisis de regresión</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Ratio
##           Df  Sum Sq  Mean Sq F value Pr(&gt;F)
## Día        2 0.15370 0.076852  0.7465 0.5134
## Residuals  6 0.61772 0.102953</code></pre>
<pre><code>## $emmeans
##  Día   emmean        SE df lower.CL upper.CL
##  1   4.540136 0.1852507  6 4.086844 4.993428
##  7   4.547998 0.1852507  6 4.094706 5.001290
##  10  4.266929 0.1852507  6 3.813637 4.720221
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast        estimate        SE df t.ratio p.value
##  Día1 - Día7  -0.00786201 0.2619841  6  -0.030  0.9995
##  Día1 - Día10  0.27320673 0.2619841  6   1.043  0.5796
##  Día7 - Día10  0.28106874 0.2619841  6   1.073  0.5631
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-109-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="sólidos-solubles" class="section level2">
<h2>Sólidos solubles</h2>
<pre><code>## # A tibble: 3 × 4
##   Día       n Mean_Solidos sd_Solidos
##   &lt;fct&gt; &lt;int&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 1         3         9.33      0.467
## 2 7         3         7.73      0.533
## 3 10        3         6.73      0.769</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-112-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Modelo</p>
<pre><code>## lm(formula = Solidos ~ Día, data = data)</code></pre>
<p>Análisis de regresión</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Solidos
##           Df  Sum Sq Mean Sq F value   Pr(&gt;F)   
## Día        2 10.3200  5.1600  14.159 0.005345 **
## Residuals  6  2.1867  0.3644                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## $emmeans
##  Día   emmean        SE df lower.CL  upper.CL
##  1   9.333333 0.3485419  6 8.480482 10.186185
##  7   7.733333 0.3485419  6 6.880482  8.586185
##  10  6.733333 0.3485419  6 5.880482  7.586185
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast     estimate        SE df t.ratio p.value
##  Día1 - Día7       1.6 0.4929127  6   3.246  0.0402
##  Día1 - Día10      2.6 0.4929127  6   5.275  0.0045
##  Día7 - Día10      1.0 0.4929127  6   2.029  0.1861
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><img src="Ensayo8_files/figure-html/unnamed-chunk-117-1.png" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="pca" class="section level2">
<h2>PCA</h2>
<pre><code>## Importance of components:
##                           PC1    PC2       PC3
## Standard deviation     3.4037 1.5539 4.403e-16
## Proportion of Variance 0.8275 0.1725 0.000e+00
## Cumulative Proportion  0.8275 1.0000 1.000e+00</code></pre>
<pre><code>##      a_color          ATT    aao_0.125  Respiración      Fenoles 
##    8.6293819    8.6255089    8.6168928    8.5762641    8.4718789 
##      Sólidos      Firmeza      L_color           pH      b_color 
##    8.3931017    8.2051790    8.1007581    7.9548838    7.3240295 
##        Clo_a        Clo_b        Ratio Carotenoides 
##    6.5160138    6.4679490    3.7801160    0.3380426</code></pre>
<pre><code>## Carotenoides        Ratio        Clo_b        Clo_a      b_color 
##  39.79155808  23.27689434  10.38098703  10.15037784   6.27361361 
##           pH      L_color      Firmeza      Sólidos      Fenoles 
##   3.24684879   2.54696102   2.04596180   1.14433045   0.76636676 
##  Respiración    aao_0.125          ATT      a_color 
##   0.26553869   0.07060736   0.02926830   0.01068594</code></pre>
<p>Biplot
<img src="Ensayo8_files/figure-html/unnamed-chunk-123-1.png" width="95%" style="display: block; margin: auto;" /></p>
<p>Análisis de componentes principales para las variables fisicoquímicas
de frutos de H. edulis cosechados en Gualeguaychú en noviembre de 2023 y
conservados a 1°C a los 1, 7 y 10 días.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
