---
title: "Suelo en Entre Ríos"

---

```{r, echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

#Load library
library(readxl)

#Create object "aqua" which contains aquaterr data
suelo <- read_excel("database.xlsx", sheet = "II suelo")

suelo$Sitio<-as.factor(suelo$Sitio)
suelo$Micrositio<-as.factor(suelo$Micrositio)
suelo$CE<-as.numeric(suelo$CE)
suelo$H2O_saturacion<-as.numeric(suelo$H2O_saturacion)
suelo$pH_agua<-as.numeric(suelo$pH_agua)
suelo$pH_CaCl2<-as.numeric(suelo$pH_CaCl2)
suelo$pH_KCl<-as.numeric(suelo$pH_KCl)
suelo$MO<-as.numeric(suelo$MO)
suelo$CO<-as.numeric(suelo$CO)
suelo$NO<-as.numeric(suelo$NO)
suelo$C_N<-as.numeric(suelo$C_N)
suelo$Sitio<-factor(suelo$Sitio,levels=c("Concordia", "Palmar","Gualeguaychu"))

```

```{r, echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

# Crea un vector con las variables respuesta
variables_respuesta_suelo <- c("CE", "H2O_saturacion","pH_agua", "pH_CaCl2","pH_KCl", "MO","CO", "NO","C_N")

# Inicializa una lista para almacenar las tablas y otra lista para los gráficos
tablas_ER_suelo <- list()
graficos_ER_suelo <- list()

library(dplyr)

for(variable in variables_respuesta_suelo) {
  # Crea la tabla resumen
  assign(paste0("ER_suelo_", variable), suelo %>%
    dplyr::group_by(Sitio) %>%
    dplyr::summarise(n = n(),
                      Mean = mean(.data[[variable]]),
                      sd = sd(.data[[variable]]),
                      min = min(.data[[variable]]),
                      max = max(.data[[variable]]))
  )

  # Agrega la tabla a la lista
  tablas_ER_suelo[[variable]] <- get(paste0("ER_suelo_", variable))

  # Crea el gráfico
  library(ggplot2)
gg_plot <- ggplot(tablas_ER_suelo[[variable]], aes(x = Sitio, y = Mean, fill = Sitio)) +
  scale_fill_manual(values = c("coral4","burlywood2","palegreen4")) +
  stat_summary(fun = "mean", size = 1, geom = "bar") +
  geom_errorbar(aes(ymin = min, ymax = max), width = 0.5) +
  theme_classic() +
  theme(legend.title = element_blank()) +
  theme(legend.position = "none") +
  theme(text = element_text(size = 15, color = 'black')) +
  theme(axis.text = element_text(color = 'black')) +
  labs(y=paste0("", variable), x="")

assign(paste0("ER_suelo_gg_", variable), gg_plot)

    # Agrega el gráfico a la lista
graficos_ER_suelo[[variable]] <- get(paste0("ER_suelo_gg_", variable))

}


```

Gráficos de suelo
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggpubr)
ER_gg_soil <- ggarrange(plotlist = graficos_ER_suelo, ncol = 3, nrow = 3)
ER_gg_soil
```

Diferencia relativa de la humedad de suelo en % durante la primavera de 2022
```{r, echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

#Load library
library(readxl)

#Create object "aqua" which contains aquaterr data
aqua <- read_excel("database.xlsx", sheet = "II aquaterr")

aqua$moisture<-as.numeric(aqua$moisture)
aqua$date<-as.factor(aqua$date)
aqua$phenotype<-as.factor(aqua$phenotype)
aqua$site<-as.factor(aqua$site)
aqua$cardinal_point<-as.factor(aqua$cardinal_point)
aqua$site<-factor(aqua$site,levels=c("concordia", "palmar","gualeguaychu"))
aqua$date<-factor(aqua$date,levels=c("september", "november"))


```

```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)
aqua_phenotype<-ggplot(aqua, aes(x=phenotype, y=moisture, color=site)) +
  geom_point()+
  geom_boxplot()+
  scale_color_manual(values=c("coral1","burlywood2","palegreen4"))+
  facet_grid(.~date)+
  labs(y="%", x="phenotype")+
  theme_classic()+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='black'))+
  theme(axis.text = element_text(color='black'))+
  theme(legend.title=element_blank())+
  theme(legend.position = "bottom")+
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1))+
  ylim(0,100)
aqua_phenotype

```

```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)
aqua_site<-ggplot(aqua, aes(x=site, y=moisture, color=site, width=1)) +
  geom_boxplot()+
  geom_point()+
  scale_color_manual(values=c("coral1","burlywood2","palegreen4"))+
  facet_grid(.~date)+
  labs(y="%", x="site")+
  theme_classic()+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=20, color='black'))+
  theme(axis.text = element_text(color='black'))+
  theme(legend.title=element_blank())+
  theme(legend.position = "bottom")+
  theme(axis.text.x = element_text(angle = 0, vjust = 1, hjust=1))+
  ylim(0,100)
aqua_site

```

```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

aqua_site<-ggplot(data = aqua, aes(x = site, y = moisture, fill=site))+
  stat_summary(fun = "mean", size = 0.5, geom = "bar", position = "dodge2")+
  geom_errorbar(aes(ymin=MEAN-sd, ymax=MEAN+sd), width=0.2,position = position_dodge(1))+
  
  theme_classic()+
  scale_fill_manual(values=c("coral", "coral4"))+
  labs(y="Peso (g)", x="")+
  theme(legend.title=element_blank())+
  theme(legend.position = "none")+
  theme(panel.grid.major.y = element_line(size=0.5, color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=30, color="black"))+
  theme(axis.text = element_text(color="black"))+
  theme(plot.background = element_rect(fill = "white"))+
  theme(panel.background = element_rect(fill = "white", color = "white"))+
  theme(axis.text.x = element_blank())

```


```{r, echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(Rmisc)
estadaqua_date <- summarySE(aqua, measurevar="moisture", groupvars=c("date","site"))
estadaqua_date

```

```{r, echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)
aqua_date<-ggplot(aqua, aes(x=phenotype, y=moisture, color=date, width=1)) +
  geom_point(width=2)+
  scale_color_manual(values=c("green","violet"))+
  labs(y="%", x="phenotype")+
  theme_classic()+
  theme(panel.grid.major.y = element_line(size=0.05, color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=20, color='black'))+
  theme(axis.text = element_text(color='black'))+
  theme(legend.title=element_blank())+
  theme(legend.position = "bottom")+
  geom_hline(yintercept =56.06952, color = "violet")+
  geom_hline(yintercept =68.12500, color= "green")+
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1))
aqua_date

```

```{r, echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)
aqua_date2<-ggplot(aqua, aes(x=date, y=moisture, color=date, width=0.5)) +
  geom_boxplot(size=1)+
  scale_color_manual(values=c("green","violet"))+
  labs(y="%", x="date")+
  theme_classic()+
  theme(panel.grid.major.y = element_line(size=0.05, color='black'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=20, color='black'))+
  theme(axis.text = element_text(color='black'))+
  theme(legend.title=element_blank())+
  theme(legend.position = "bottom")#+
  # geom_hline(yintercept =56.06952, color = "green")+
  # geom_hline(yintercept =68.12500, color= "violet")
aqua_date2

```

```{r, echo=FALSE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

# aqua_sep<-subset(aqua, date == "september")
# aqua_nov<-subset(aqua, date == "november")
# max(aqua_sep$moisture)
# min(aqua_sep$moisture)
# max(aqua_nov$moisture)
# min(aqua_nov$moisture)


```

