<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Polinización</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
  <link rel="icon" type="image/png" href="fruto.jpg"/>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Inicio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">I Introducción</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    II Sitios
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="II_Phenotypes.html">Fenotipos</a>
    </li>
    <li>
      <a href="II_maps1.html">Mapas</a>
    </li>
    <li>
      <a href="II_ER_Climate.html">Clima</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">ENTRE RÍOS</li>
    <li class="divider"></li>
    <li>
      <a href="II_ER_SMN.html">MET ER</a>
    </li>
    <li>
      <a href="II_ER_DL.html">DL ER</a>
    </li>
    <li>
      <a href="II_ER_Soil.html">Suelos ER</a>
    </li>
    <li>
      <a href="II_ER_Asociatedspecies.html">Especies asociadas</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">MORENO</li>
    <li class="divider"></li>
    <li>
      <a href="II_M_inta.html">MET M</a>
    </li>
    <li>
      <a href="II_M_Soil.html">Suelos M</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    III Fenología
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="III_Flowers.html">Fenología</a>
    </li>
    <li>
      <a href="III_Yield.html">Rendimiento</a>
    </li>
    <li>
      <a href="III_Polinization.html">Polinización</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    IV Maduración
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mad_resume.html">Tablas resumen</a>
    </li>
    <li>
      <a href="madPhysical.html">Atributos físicos</a>
    </li>
    <li>
      <a href="madAntioxidant.html">Actividad antioxidante</a>
    </li>
    <li>
      <a href="madPhenols.html">Fenoles</a>
    </li>
    <li>
      <a href="madSSyAcidez.html">Sólidos Solubles y Acidez</a>
    </li>
    <li>
      <a href="madAcids.html">Ácidos orgánicos</a>
    </li>
    <li>
      <a href="madCarbohydrates.html">Carbohidratos</a>
    </li>
    <li>
      <a href="madFiber.html">Fibra dietaria</a>
    </li>
    <li>
      <a href="madCations.html">Cationes</a>
    </li>
    <li>
      <a href="mad_PCA.html">Multivariado</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    V Postcosecha
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Ensayo1.html">Ensayo 1</a>
    </li>
    <li>
      <a href="Ensayo2.html">Ensayo 2</a>
    </li>
    <li>
      <a href="Ensayo3.html">Ensayo 3</a>
    </li>
    <li>
      <a href="Ensayo4.html">Ensayo 4</a>
    </li>
    <li>
      <a href="Ensayo5.html">Ensayo 5</a>
    </li>
    <li>
      <a href="Ensayo6.html">Ensayo 6</a>
    </li>
    <li>
      <a href="Ensayo7.html">Ensayo 7</a>
    </li>
    <li>
      <a href="Ensayo8.html">Ensayo 8</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    VI Variabilidad
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="V_Weight.html">Peso</a>
    </li>
    <li>
      <a href="V_Diameter.html">Diámetro</a>
    </li>
    <li>
      <a href="V_Seeds.html">Semillas</a>
    </li>
    <li>
      <a href="V_Colorimetry.html">Colorimetría</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="V_phenols.html">Fenoles</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="V_flowers.html">Variables reproductivas</a>
    </li>
    <li>
      <a href="V_Branches.html">Eficiencia reproductiva</a>
    </li>
    <li>
      <a href="V_fruits.html">Frutos</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Otros ensayos
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Genetics.html">Extracción de ADN</a>
    </li>
    <li>
      <a href="extraction_methods.html">Extración química</a>
    </li>
    <li>
      <a href="q2022_quimico.html">Variables químicas 2022</a>
    </li>
    <li>
      <a href="secado.html">Secado ER</a>
    </li>
    <li>
      <a href="dry_test.html">Pruebas de Secado</a>
    </li>
    <li>
      <a href="calafate.html">Calafate</a>
    </li>
    <li>
      <a href="microprop.html">Micropropagación</a>
    </li>
  </ul>
</li>
<li>
  <a href="publications.html">Publicaciones</a>
</li>
<li>
  <a href="bibliografia.html">Bibliografía</a>
</li>
<li>
  <a href="about.html">Sobre el sitio</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/ipovilonis/ubajay.github.io">
    <span class=" favicon.ico"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Polinización</h1>

</div>


<div id="objetive" class="section level2">
<h2>Objetive</h2>
<p>The objective of this essay was to study the pollination regime of
the species.</p>
</div>
<div id="materials-and-methods" class="section level2">
<h2>Materials and Methods</h2>
<p>Pollination studies were carried out on floral buds that had not
begun anthesis yet. In the <strong>natural self-pollinated</strong>
(NSPO) treatment, branches with only one bud were isolated with paper
bags , in <strong>natural self-pollinated</strong> (NSPS) branches with
several buds were isolated with paper bags to check auto compatibility,
while in the <strong>open pollination</strong> (OP) treatment branches
were only identified. In the <strong>cross-pollinated</strong> (CPA)
trial, buds were emasculated and then pollinated manually with pollen
from another genotype and in <strong>cross pollinated</strong> (CPS) the
buds were emasculated and then pollinated manually with pollen from
anothers flowers on the same genotype. These branches were also covered
with paper bags to avoid the entrance of unknown pollen. Twenty
repetitions of each treatment were performed in random branches.
Finally, thirty days later fruit set was verified.</p>
</div>
<div id="results" class="section level2">
<h2>Results</h2>
<p><img src="III_Polinization_files/figure-html/unnamed-chunk-3-1.png" width="1440" style="display: block; margin: auto;" /></p>
<p><img src="III_Polinization_files/figure-html/unnamed-chunk-6-1.png" width="1440" style="display: block; margin: auto;" /><img src="III_Polinization_files/figure-html/unnamed-chunk-6-2.png" width="1440" style="display: block; margin: auto;" /></p>
<pre><code>## [1] 0.337784426</code></pre>
<pre><code>## 
## Call:
## glm(formula = PROP ~ Tratamiento, family = &quot;quasibinomial&quot;, data = polin, 
##     weights = TOTAL)
## 
## Coefficients:
##                    Estimate  Std. Error  t value        Pr(&gt;|t|)    
## (Intercept)       -1.308333    0.207142 -6.31612 0.0000000085844 ***
## TratamientoCPS   -20.575487 3148.861919 -0.00653         0.99480    
## TratamientoNSPO  -20.257736 3799.004878 -0.00533         0.99576    
## TratamientoNSPS  -21.366645 2656.260476 -0.00804         0.99360    
## TratamientoOP     -1.524881    0.320182 -4.76254 0.0000068477041 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasibinomial family taken to be 0.337784426)
## 
##     Null deviance: 67.66800  on 99  degrees of freedom
## Residual deviance: 33.72519  on 95  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 20</code></pre>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: PROP
##             LR Chisq Df             Pr(&gt;Chisq)    
## Tratamiento 100.4866  4 &lt; 0.000000000000000222 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## Single term deletions
## 
## Model:
## PROP ~ Tratamiento
##             Df Deviance scaled dev.               Pr(&gt;Chi)    
## &lt;none&gt;         33.72519                                       
## Tratamiento  4 67.66800    100.4866 &lt; 0.000000000000000222 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## Single term deletions
## 
## Model:
## PROP ~ Tratamiento
##             Df Deviance scaled dev.               Pr(&gt;Chi)    
## &lt;none&gt;         33.72519                                       
## Tratamiento  4 67.66800    100.4866 &lt; 0.000000000000000222 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## $emmeans
##  Tratamiento         prob           SE  df    asymp.LCL   asymp.UCL
##  CPA         0.2127659574 0.0346955588 Inf 0.1526037900 0.288569407
##  CPS         0.0000000003 0.0000009866 Inf 0.0000000000 1.000000000
##  NSPO        0.0000000004 0.0000016355 Inf 0.0000000000 1.000000000
##  NSPS        0.0000000001 0.0000003773 Inf 0.0000000000 1.000000000
##  OP          0.0555555556 0.0128103174 Inf 0.0351707041 0.086693790
## 
## Confidence level used: 0.95 
## Intervals are back-transformed from the logit scale 
## 
## $contrasts
##  contrast    odds.ratio            SE  df null z.ratio p.value
##  CPA / CPS    862621658 2716276490779 Inf    1   0.007  1.0000
##  CPA / NSPO   627802198 2385023611543 Inf    1   0.005  1.0000
##  CPA / NSPS  1902900753 5054600060808 Inf    1   0.008  1.0000
##  CPA / OP             5             1 Inf    1   4.763  &lt;.0001
##  CPS / NSPO           1          3591 Inf    1   0.000  1.0000
##  CPS / NSPS           2          9088 Inf    1   0.000  1.0000
##  CPS / OP             0             0 Inf    1  -0.006  1.0000
##  NSPO / NSPS          3         14051 Inf    1   0.000  1.0000
##  NSPO / OP            0             0 Inf    1  -0.005  1.0000
##  NSPS / OP            0             0 Inf    1  -0.007  1.0000
## 
## P value adjustment: tukey method for comparing a family of 5 estimates 
## Tests are performed on the log odds ratio scale</code></pre>
<p>Plot 1</p>
<p><img src="III_Polinization_files/figure-html/unnamed-chunk-8-1.png" width="1440" style="display: block; margin: auto;" /></p>
<p>Plot 2</p>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Only treatments <strong>open pollination [OP]</strong> (5.56%) and
<strong>artificial cross-pollinated [CPA]</strong> (21.28%) presented
fruit set. Therefore the species is self-incompatible.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
