---
title: "Tablas resumen"
output:
 html_document:
   toc: true
   toc_depth: 5
   toc_float:
     collapsed: false
     smooth_scroll: true
---

##  4.1. Atributos de calidad

| Estado        | PFF           | PSF          | CAF          | DMIF         | DMAF         | DPF          | PSS          | PSS/PSF      |
|:-------------:|:-------------:|:------------:|:------------:|:------------:|:------------:|:------------:|:------------:|:------------:|
| Inmaduro      | 19,5±2,1b     | 4,1±0,6a     | 79,4±1,0c    | 31,4±1,4b    | 34,3±1,4b    | 36,3±2,2a    | 2,2±0,4a     | 0,55±0,6a    |
| Medio Maduro  | 40,1±4,4a     | 6,6±1,0a     | 83,5±0,9b    | 41,4±1,9a    | 47,6±2,0a    | 43,8±2,7a    | 3,5±0,6a     | 0,53±0,6a    |
| Maduro        | 39,6±4,3a     | 5,0±0,7a     | 87,5±0,8a    | 42,4±1,9a    | 48,5±2,0a    | 38,6±2,3a    | 3,0±0,5a     | 0,63±0,7a    |
| Sobre Maduro  | 39,5±4,3a     | 7,1±1,0a     | 82,2±0,9bc   | 44,4±2,0a    | 48,7±2,0a    | 35,7±2,2a    | 2,8±0,5a     | 0,56±0,6a    |
| *χ^2*         | *28,506*      | *8,919*      | *41,480*     | *34,787*     | *47,978*     | *7,082*      | *4,133*      | *1,899*      |
| *p*           | *<0,001*      | *0,030*      | *<0,001*     | *<0,001*     | *<0,001*     | *0,069*      | *0,247*      | *0,594*      |

##  4.2. Color

| Estado        | *L            | *a           | *b           |
|:-------------:|:-------------:|:------------:|:------------:|
| Inmaduro      | 68,7±0,5b     | 1,3±0,2b     | 6,8±1,7ab    |
| Medio Maduro  | 67,7±0,5b     | 4,2±0,5a     | 5,4±1,7b     |
| Maduro        | 72,3±0,5a     | 5,7±1,4ab    | 12,3±1,7a    |
| Sobre Maduro  | 71,5±0,5a     | 4,3±0,6a     | 6,8±1,7ab    |
| *F*           | *23,797*      | *17,228*     | *3,811*      |
| *p*           | *<0,001*      | *<0,001*     | *<0,040*     |

##  4.3 Sólidos solubles, acidez total titulable, Fenoles totales y actividad antioxidante

| Estado        | SS (°Brix)    | pHi           | ATT %         | SS/ATT        | PT (mg/100g PFF) | DPPH Inh (%)  |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:----------------:|
| Inmaduro      | 7,6±0,03c     | 3,4±0,1a      | 1,8±0,1a      | 4,3±0,2b      | 905,8±101,7a  | 94,7±6,7a        |
| Medio Maduro  | 6,0±0,03d     | 3,2±0,1a      | 1,6±0,0ab     | 3,7±0,2b      | 426,2±26,7a   | 62,0±24,9b       |
| Maduro        | 8,2±0,03b     | 2,3±0,1b      | 1,8±0,2a      | 4,5±0,2b      | 337,4±13,7a   | 80,1±17,8ab      |
| Sobre Maduro  | 10,1±0,03a    | 3,4±0,1a      | 1,4±0,1b      | 7,3±0,2a      | 130,4±3,3b    | 22,±30,0c        |
| *X^2*         |               |               |               |               |               | *183,720*        |
| *F*           | *2.068,470*   | *15,785*      | *9,311*       | *77,299*      | *128,163*     |                  |
| *p*           | *<0,001*      | *0,001*       | *0,006*       | *<0,001*      | *<0,001*      | *<0,001*         |

##  4.4 Ácidos orgánicos

| Estado        | TAR (mg/g)    | MAL (mg/g)    | QUI (mg/g)    | SUC (mg/g)    |
|:-------------:|:------------:|:-------------:|:-------------:|:-------------:|
| Inmaduro      | 0,00±0,10b    | 44,90±8,33c   | 0,37±0,24b    | 112,33±3,31a |
| Medio Maduro  | 0,00±0,10b    | 90,19±2,85b   | 25,25±1,80a   | 92,48±3,31b  |
| Maduro        | 0,00±0,10b    | 105,14±1,95a  | 22,62±1,09a   | 99,43±3,31b  |
| Sobremaduro   | 0,94±0,10a    | 84,79±2,34b   | 22,85±1,78a   | 115,65±3,31a |
| *F*           | *26,039*      | *77,887*      | *262,20*      | *12,398*      |
| *P*           | *<0,001*      | *<0,001*      | *<0,001*      | *<0,001*      |

##  4.5 Carbohidratos

| Estado        | SAC (mg/g)    | GLU (mg/g)    | FRU (mg/g)    | TS (mg/g)     | GLU/FRU      | ALM (mg/g)   | TS/TA        |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:------------:|:------------:|:------------:|
| Inmaduro      | 21,2±4,8c     | 95,6±2,4b     | 150,1±6,5bc   | 266,9±11,2c   | 0,63±0,01b   | 171,4±19,4a   | 1,7±0,09ab   |
| Medio Maduro  | 77,8±4,8ab    | 89,5±5,9b     | 134,4±6,5c    | 301,7±11,2c   | 0,66±0,00b   | 161,2±19,4a   | 1,4±0,09b    |
| Maduro        | 82,5±4,8a     | 105,0±77,6b   | 163,1±6,5b    | 350,6±11,2b   | 0,64±0,00b   | 40,5±19,4b    | 1,5±0,09ab   |
| Sobremaduro   | 59,4±4,8b     | 163,1±6,6a    | 205,9±6,5a    | 428,4±11,2a   | 0,79±0,00a   | 66,0±19,4b    | 1,9±0,09a    |
| *F*           | *33,672*      | *42,000*      | *33,661*      | *39,998*      | *118,100*    | *11,705*     | *4,973*      |
| *P*           | *<0,001*      | *<0,001*      | *<0,001*      | *<0,001*      | *<0,001*     | *0,003*      | *0,046*      |

##  4.6 Fibras

| Estado        | FDI (g/100g)  | FDS (g/100g)  | FDT (g/100g)  |
|:-------------:|:-------------:|:-------------:|:-------------:|
| Inmaduro      | 26,71±1,68a   | 9,03±1,35a    | 35,74±2,22ab  |
| Medio Maduro  | 27,13±1,68a   | 9,67±1,35a    | 36,80±2,22a   |
| Maduro        | 15,81±1,68b   | 11,26±1,35a   | 27,07±2,22ab  |
| Sobremaduro   | 15,51±1,68b   | 10,44±1,35a   | 25,94±2,22b   |
| *F*           | *14,895*      | *0,505*       | *6,511*       |
| *p*           | *0,001*       | *0,689*       | *0,015*       |

##  4.7 Perfíl de compuestos fenólicos

| Pico número  | Biofenol           | Tiempo de retención (min) | λ (nm)  | Inmaduro    | Medio maduro  | Maduro      | Sobre-maduro | *F*      | *p*      |
|:------------:|:------------------:|:--------------------------:|:-------:|:-----------:|:-------------:|:-----------:|:------------:|:--------:|:-------:|
| 1            | Ácido gálico       | 6,49                       | 215,271 | 271±4a      | 132±5b        | 117±3c      | 80±2d        | *1078*   | *<0,001* |
| 2            | Derivado de galoil | 10,4                       | 223,257 | 1238±7a     | 524±55b       | 350±6c      | 42±7d        | *599,6*  | *<0,001* |
| 3            | Catecol            | 12,5                       | 220,285 | 829±47a     | 166±12b       | 360±5c      | 53±8d        | *224,2*  | *<0,001* |
| 4            | Derivado de galoil | 13,2                       | 220,260 | 1192±18a    | 591±83b       | 173±12c     | 47±6d        | *186,8*  | *<0,001* |
| 5            | Derivado de galoil | 16,5                       | 220,275 | 498±22a     | 517±74a       | 175±9b      | 94±25b       | *22,6*   | *0,006*  |
| 6            | Derivado de galoil | 17,6                       | 220,271 | 951±15a     | 1088±70a      | 492±19b     | 124±24c      | *228,8*  | *<0,001* |
| 7            | Ácido siríngico     | 20,5                       | 218,276 | 278±30a     | 103±22b       | 108±13b     | 30±7c        | *54,43*  | *0,001*  |
| 8            | Catequina          | 22,1                       | 215,279 | 373±40a     | 130±18b       | 122±15b     | 71±9c        | *24,25*  | *0,005*  |
| 9            | Ácido tánico       | 24,5                       | 280,000 | 54±4b       | 178±52a       | 218±7a      | 181±1a       | *11,97*  | *0,018*  |
| 10           | Ácido tánico       | 25,8                       | 283,000 | 58±3c       | 505±35b       | 791±33a     | 726±60a      | *168,6*  | *<0,001* |
| 11           | Rutina             | 30,6                       | 253,363 | 135±4a      | 45±16b        | 21±4b       | 40±2b        | *46,56*  | *0,001*  |
| Fenoles totales |                  |                            |         | 5877±60a    | 3981±95b      | 2735±182c   | 1488±67d     | *459,3*  | *<0,001* |

##  4.8 Clorofilas

| Estado        | Clorofila a    | Feofitina a    | Clorofila b    | Feofitina b    |
|:-------------:|:--------------:|:--------------:|:--------------:|:--------------:|
| Inmaduro      | 5,5 ± 1,4a     | 24,6 ± 7,2a    | 18,7 ± 5,7a    | 5,45 ± 1,3     |
| Medio Maduro  | 3,7 ± 0,4a     | 17,5 ± 4,4b    | 9,0 ± 1,4b     | 5,5 ± 0,8      |
| Maduro        |                | 7,9 ± 1,2c     | 12,0 ± 1,7c    | 4,6 ± 0,1c     |
| Sobremaduro   |                | 5,9 ± 1,6c     |                | 5,9 ± 0,9      |
| *F*           | *12,26*        | *8,12*         | *13,28*        | *0,16*         |
| *P*           | *0,151*        | *0,008*        | *0,002*        | *0,8552*       |

##  4.9 Carotenoides

| Estado        | Luteína         | β-criptoxantina | β-caroteno      | Ésteres de β-criptoxaninas (picos 4+5) | Luteína diesteres (picos 6+7+8) |
|:-------------:|:---------------:|:---------------:|:---------------:|:----------------------------------------:|:-------------------------------:|
| Inmaduro      | 297,7 ± 8,4a    | 4,3 ± 1,3a      | 56,3 ± 13,9a    | 24,8 ± 1,7a                             | 51,7 ± 7,9a                   |
| Medio Maduro  | 242,9 ± 6,4a    | 45,5 ± 11,5b    | 59,5 ± 1,2a     | 174,8 ± 20,3b                           | 119,5 ± 11,4b                 |
| Maduro        | 265,1 ± 40,5a   | 50,1 ± 5,0b     | 44,7 ± 8,1a     | 174,5 ± 12,9b                           | 172,1 ± 12,4c                 |
| Sobremaduro   | 290,6 ± 50,9a   | 92,7 ± 24,2c    | 91,2 ± 25,4b    | 409,4 ± 52,1c                           | 194,3 ± 52,8c                 |
| *F*           | *0,11*          | *22,56*         | *14,86*         | *92,08*                                 | *35,09*                       |
| *P*           | *0,951*         | *<0,001*        | *<0,001*        | *<0,001*                                | *<0,001*                      |

##  4.10 Cationes

| Estados       | Mg (mg/g)       | K (mg/g)        | Mn (mg/g)       | TC (mg/g)       |
|:-------------:|:---------------:|:---------------:|:---------------:|:---------------:|
| Inmaduro      | 0,33 ± 0,10a    | 20,63 ± 7,63a   | 0,00 ± 0,00a    | 20,97 ± 7,74a   |
| Medio maduro  | 0,34 ± 0,03a    | 20,69 ± 2,55a   | 0,01 ± 0,01a    | 21,05 ± 2,57a   |
| Maduro        | 0,40 ± 0,02a    | 22,85 ± 2,73a   | 0,00 ± 0,00a    | 23,27 ± 2,76a   |
| Sobremaduro   | 0,24 ± 0,04a    | 17,57 ± 3,14a   | 0,00 ± 0,00a    | 17,82 ± 3,17a   |
| *F*           | *3,559*         | *0,761*         | *2,815*         | *0,787*         |
| *p*           | *0,087*         | *0,556*         | *0,130*         | *0,543*         |

