<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Acids</title>

<script src="site_libs/header-attrs-2.22/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/darkly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
  <link rel="icon" type="image/png" href="fruto.jpg"/>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Hexachlamys edulis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Phenotypes2.html">Phenotypes</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Fruit Variability
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Weight.html">Weight</a>
    </li>
    <li>
      <a href="Diameter.html">Diameter</a>
    </li>
    <li>
      <a href="Seeds.html">Seeds</a>
    </li>
    <li>
      <a href="Colorimetry.html">Colorimetry</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="phenols.html">Phenols</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="Reproductive.html">Reproductive</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="Multivariate.html">Multivariate</a>
    </li>
    <li class="divider"></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Maturity
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Maturity.html">Summary tables</a>
    </li>
    <li>
      <a href="madPhysical.html">Physical variables</a>
    </li>
    <li>
      <a href="madAntioxidant.html">Antioxidant Activity</a>
    </li>
    <li>
      <a href="madAcids.html">Organic Acids</a>
    </li>
    <li>
      <a href="madCarbohydrates.html">Carbohydrates</a>
    </li>
    <li>
      <a href="madFiber.html">Dietary Fiber</a>
    </li>
    <li>
      <a href="madCations.html">Cations</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Essays
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Phenology.html">Phenology</a>
    </li>
    <li>
      <a href="Polinization.html">Polinization</a>
    </li>
    <li>
      <a href="Branches.html">Branches</a>
    </li>
    <li>
      <a href="Yield.html">Yield</a>
    </li>
    <li>
      <a href="Postharvest.html">Postharvest</a>
    </li>
    <li>
      <a href="climateric2.html">Climacteric</a>
    </li>
    <li>
      <a href="climateric3.html">Climacteric color</a>
    </li>
    <li>
      <a href="Companionspecies.html">Companion species</a>
    </li>
    <li>
      <a href="Climate.html">Climate</a>
    </li>
    <li>
      <a href="Soil.html">Soil</a>
    </li>
    <li>
      <a href="Genetics.html">Genetics</a>
    </li>
    <li>
      <a href="extraction_methods.html">Extraction methods</a>
    </li>
  </ul>
</li>
<li>
  <a href="publications.html">Academic Publications</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/ipovilonis/ubajay.github.io">
    <span class=" favicon.ico"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Acids</h1>

</div>


<div id="acidos-orgánicos-en-peso-fresco" class="section level2">
<h2>Acidos orgánicos en peso fresco</h2>
<div
id="concentración-del-perfíl-de-ácidos-orgánicos-a-distintos-estados-de-maturity"
class="section level3">
<h3>Concentración del perfíl de ácidos orgánicos a distintos estados de
Maturity</h3>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;dataAT&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;dataato&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;aci6s&#39; not found</code></pre>
</div>
<div id="tabla-descriptiva" class="section level3">
<h3>Tabla descriptiva</h3>
<pre><code>##    CAR MAD  N     CONF         sd         se         ci
## 1  ATT   I  3 1.779200 0.05079843 0.02932848 0.12619028
## 2  ATT  MM  3 1.606400 0.02789695 0.01610631 0.06929987
## 3  ATT   M  3 1.828267 0.20390638 0.11772541 0.50653154
## 4  ATT  SM  3 1.384533 0.08352756 0.04822466 0.20749396
## 5 &lt;NA&gt;   I 24 6.659458 8.13360208 1.66026457 3.43451894
## 6 &lt;NA&gt;  MM 24 6.325996 5.04552019 1.02991250 2.13053632
## 7 &lt;NA&gt;   M 24 6.354450 5.28334578 1.07845844 2.23096126
## 8 &lt;NA&gt;  SM 24 6.954696 5.87462880 1.19915358 2.48063818</code></pre>
</div>
<div id="evolución-del-perfíl-de-ácidos-orgánicos-en-la-maduración"
class="section level3">
<h3>Evolución del perfíl de ácidos orgánicos en la maduración</h3>
<p><img src="madAcids_files/figure-html/unnamed-chunk-4-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="acidos-orgánicos-totales" class="section level3">
<h3>Acidos orgánicos Totales</h3>
<div
id="concentración-de-ácidos-orgánicos-totales-a-distintos-estados-de-maturity."
class="section level4">
<h4>Concentración de ácidos orgánicos totales a distintos estados de
Maturity.</h4>
<p><img src="madAcids_files/figure-html/unnamed-chunk-6-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="tabla-descriptiva-totales" class="section level4">
<h4>Tabla descriptiva totales</h4>
<pre><code>##        CAR MAD N    TOTALF          sd          se         ci
## 1    ACIDS   I 6 26.637833 1.990422128 0.812586431 2.08881992
## 2    ACIDS  MM 6 25.303985 1.788299193 0.730070088 1.87670491
## 3    ACIDS   M 6 25.417800 0.434147222 0.177239861 0.45560957
## 4    ACIDS  SM 6 27.818783 1.061812544 0.433483156 1.11430393
## 5  CATIONS   I 3  3.590633 1.325520714 0.765289741 3.29277599
## 6  CATIONS  MM 3  2.560667 0.313536989 0.181020665 0.77886906
## 7  CATIONS   M 3  2.603833 0.308997643 0.178399872 0.76759270
## 8  CATIONS  SM 3  2.214367 0.394508331 0.227769491 0.98001302
## 9     STAT   I 3  1.721122 0.263331774 0.152034671 0.65415239
## 10    STAT  MM 3  1.447652 0.116290944 0.067140608 0.28888272
## 11    STAT   M 3  1.541716 0.132691311 0.076609364 0.32962349
## 12    STAT  SM 3  1.909504 0.007733365 0.004464861 0.01921074
## 13  SUGARS   I 6 45.629848 4.811537421 1.964301927 5.04939885
## 14  SUGARS  MM 6 36.768222 5.141036221 2.098819248 5.39518664
## 15  SUGARS   M 6 39.159254 2.599418252 1.061208058 2.72792216
## 16  SUGARS  SM 6 53.119643 1.842284986 0.752109696 1.93335952</code></pre>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: dataAT 
##   Log-restricted-likelihood: -39.09968
##   Fixed: TOTALF ~ MAD 
## (Intercept)       MADMM        MADM       MADSM 
##   26.637833   -1.333847   -1.220033    1.180950 
## 
## Random effects:
##  Formula: ~1 | REP
##         (Intercept) Residual
## StdDev:   0.5444281 1.371765
## 
## Number of Observations: 24
## Number of Groups: 3</code></pre>
<p><img src="madAcids_files/figure-html/unnamed-chunk-8-1.png" width="960" style="display: block; margin: auto;" /><img src="madAcids_files/figure-html/unnamed-chunk-8-2.png" width="960" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.97767, p-value = 0.8493</code></pre>
</div>
<div id="anova" class="section level4">
<h4>Anova</h4>
<pre><code>##             numDF denDF  F-value p-value
## (Intercept)     1    18 3901.697  &lt;.0001
## MAD             3    18    4.454  0.0165</code></pre>
</div>
<div id="test-de-tukey" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## $emmeans
##  MAD emmean    SE df lower.CL upper.CL
##  I     26.6 0.642  2     23.9     29.4
##  MM    25.3 0.642  2     22.5     28.1
##  M     25.4 0.642  2     22.7     28.2
##  SM    27.8 0.642  2     25.1     30.6
## 
## Degrees-of-freedom method: containment 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast estimate    SE df t.ratio p.value
##  I - MM      1.334 0.792 18   1.684  0.3602
##  I - M       1.220 0.792 18   1.540  0.4354
##  I - SM     -1.181 0.792 18  -1.491  0.4629
##  MM - M     -0.114 0.792 18  -0.144  0.9989
##  MM - SM    -2.515 0.792 18  -3.175  0.0246
##  M - SM     -2.401 0.792 18  -3.032  0.0331
## 
## Degrees-of-freedom method: containment 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="madAcids_files/figure-html/unnamed-chunk-10-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="conclusiones" class="section level4">
<h4>Conclusiones</h4>
<p>Existen diferencias significativas entre estados de Maturity para los
ácidos totales detectados en este trabajo.</p>
</div>
</div>
<div id="ácido-tartárico" class="section level3">
<h3>Ácido Tartárico</h3>
<div id="modelo-y-supuestos" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Error in matrix(unlist(value), nrow = nrow(data), dimnames = list(row.names(data), : length of &#39;dimnames&#39; [2] not equal to array extent</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2&#39; not found</code></pre>
<pre><code>## Error: object &#39;tar_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;tar_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;HVtar&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;tar_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;QQtar&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2&#39; not found</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.97767, p-value = 0.8493</code></pre>
</div>
<div id="anova-1" class="section level4">
<h4>Anova</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2&#39; not found</code></pre>
</div>
<div id="test-de-tukey-1" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2&#39; not found</code></pre>
<pre><code>## $emmeans
##  method   emmean   SE df lower.CL upper.CL
##  potter_A   49.2 6.48  9   34.584     63.9
##  potter_B   48.4 6.48  9   33.754     63.1
##  rod        15.5 6.48  9    0.856     30.2
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast            estimate   SE df t.ratio p.value
##  potter_A - potter_B     0.83 9.16  9   0.091  0.9955
##  potter_A - rod         33.73 9.16  9   3.682  0.0126
##  potter_B - rod         32.90 9.16  9   3.592  0.0145
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p><img src="madAcids_files/figure-html/unnamed-chunk-14-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="conclusiones-1" class="section level4">
<h4>Conclusiones</h4>
<p>Existen diferencias significativas entre estados de Maturity. El
estado sobre maduro es el único que presenta ácido tartárico
detectable.</p>
</div>
</div>
<div id="ácido-málico" class="section level3">
<h3>Ácido málico</h3>
<div id="modelo-y-supuestos-1" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Error in matrix(unlist(value), nrow = nrow(data), dimnames = list(row.names(data), : length of &#39;dimnames&#39; [2] not equal to array extent</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2&#39; not found</code></pre>
<pre><code>## Error: object &#39;mal_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mal_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;HVmal&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mal_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;QQmal&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2&#39; not found</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.97767, p-value = 0.8493</code></pre>
</div>
<div id="anova-2" class="section level4">
<h4>Anova</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2&#39; not found</code></pre>
</div>
<div id="test-de-tukey-2" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compmal&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compmal&#39; not found</code></pre>
</div>
<div id="conclusiones-2" class="section level4">
<h4>Conclusiones</h4>
<p>Existen diferencias significativas entre estados de Maturity. En el
estado maduro se presentó el pico de concentración de ácido málico.</p>
</div>
</div>
<div id="ácido-quínico" class="section level3">
<h3>Ácido quínico</h3>
<div id="modelo-y-supuestos-2" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Error in matrix(unlist(value), nrow = nrow(data), dimnames = list(row.names(data), : length of &#39;dimnames&#39; [2] not equal to array extent</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2&#39; not found</code></pre>
<pre><code>## Error: object &#39;qui_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;qui_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;HVqui&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;qui_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;QQqui&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2&#39; not found</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.97767, p-value = 0.8493</code></pre>
<pre><code>## Error in `contrasts&lt;-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels</code></pre>
</div>
<div id="anova-3" class="section level4">
<h4>Anova</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2&#39; not found</code></pre>
</div>
<div id="test-de-tukey-3" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compqui&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compqui&#39; not found</code></pre>
</div>
<div id="conclusiones-3" class="section level4">
<h4>Conclusiones</h4>
<p>Se observa un marcado aumento de ácido quínico con la maduración
hasta frutos maduros. Luego en frutos sobre maduros Frutos medio maduros
presentan gran variabiliad.</p>
</div>
</div>
<div id="ácido-succinico" class="section level3">
<h3>Ácido succinico</h3>
<div id="modelo-y-supuestos-3" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Error in matrix(unlist(value), nrow = nrow(data), dimnames = list(row.names(data), : length of &#39;dimnames&#39; [2] not equal to array extent</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2&#39; not found</code></pre>
<pre><code>## Error: object &#39;suc_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;suc_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;HVsuc&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;suc_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;QQsuc&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2&#39; not found</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.97767, p-value = 0.8493</code></pre>
<pre><code>## Error in `contrasts&lt;-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels</code></pre>
</div>
<div id="anova-4" class="section level4">
<h4>Anova</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2&#39; not found</code></pre>
</div>
<div id="test-de-tukey-4" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compsuc&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compsuc&#39; not found</code></pre>
</div>
<div id="conclusiones-4" class="section level4">
<h4>Conclusiones</h4>
<p>Se encontraron diferencias entre estados de Maturity, los frutos
inmaduros y sobre maduros presentaron las mayores concentraciones de
ácido succínico.</p>
</div>
</div>
</div>
<div id="acidos-orgánicos-en-peso-seco" class="section level2">
<h2>Acidos orgánicos en peso seco</h2>
<div
id="concentración-del-perfíl-de-ácidos-orgánicos-a-distintos-estados-de-maturity-1"
class="section level3">
<h3>Concentración del perfíl de ácidos orgánicos a distintos estados de
Maturity</h3>
<p><img src="madAcids_files/figure-html/unnamed-chunk-27-1.png" width="1536" style="display: block; margin: auto;" /></p>
<div id="tabla-descriptiva-1" class="section level4">
<h4>Tabla descriptiva</h4>
<pre><code>##    CAR MAD  N      CONS          sd         se          ci
## 1  ATT   I  3  1.779200  0.05079843 0.02932848  0.12619028
## 2  ATT  MM  3  1.606400  0.02789695 0.01610631  0.06929987
## 3  ATT   M  3  1.828267  0.20390638 0.11772541  0.50653154
## 4  ATT  SM  3  1.384533  0.08352756 0.04822466  0.20749396
## 5 &lt;NA&gt;   I 24 39.419071 47.80778177 9.75872259 20.18745575
## 6 &lt;NA&gt;  MM 24 51.997183 41.36096715 8.44277206 17.46520468
## 7 &lt;NA&gt;   M 24 56.818384 47.30540308 9.65617497 19.97531984
## 8 &lt;NA&gt;  SM 24 56.077828 47.57987226 9.71220076 20.09121801</code></pre>
</div>
<div id="evolución-del-perfíl-de-ácidos-orgánicos-en-la-maduración-1"
class="section level4">
<h4>Evolución del perfíl de ácidos orgánicos en la maduración</h4>
<p><img src="madAcids_files/figure-html/unnamed-chunk-29-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="ácidos-orgánicos-totales" class="section level3">
<h3>Ácidos orgánicos totales</h3>
<p><img src="madAcids_files/figure-html/unnamed-chunk-30-1.png" width="960" style="display: block; margin: auto;" /></p>
<div id="tabla-descriptiva-totales-1" class="section level4">
<h4>Tabla descriptiva totales</h4>
<pre><code>##        CAR MAD N     TOTALS           sd           se          ci
## 1    ACIDS   I 6 157.676284 24.414795650  9.967298586 25.62175670
## 2    ACIDS  MM 6 207.988730 11.656957335  4.758932904 12.23322648
## 3    ACIDS   M 6 227.273538  4.284625610  1.749191081  4.49643882
## 4    ACIDS  SM 6 224.311311 13.987405810  5.710334510 14.67888217
## 5  CATIONS   I 3  20.971755  7.741948182  4.469815867 19.23206544
## 6  CATIONS  MM 3  21.053410  2.577853260  1.488324274  6.40374250
## 7  CATIONS   M 3  23.270464  2.761512785  1.594360150  6.85997805
## 8  CATIONS  SM 3  17.826367  3.175919852  1.833618181  7.88942227
## 9     STAT   I 3   1.721122  0.263331773  0.152034670  0.65415239
## 10    STAT  MM 3   1.447652  0.116290919  0.067140593  0.28888266
## 11    STAT   M 3   1.541716  0.132691300  0.076609358  0.32962346
## 12    STAT  SM 3   1.909504  0.007733369  0.004464862  0.01921075
## 13  SUGARS   I 6 266.880792  8.481943277  3.462738843  8.90125357
## 14  SUGARS  MM 6 301.680355 34.616722145 14.132217637 36.32802196
## 15  SUGARS   M 6 350.625756 31.182386756 12.730156086 32.72390800
## 16  SUGARS  SM 6 428.368083 26.752778568 10.921776116 28.07531930</code></pre>
</div>
<div id="modelo-y-supuestos-4" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: dataAT 
##   Log-restricted-likelihood: -86.62191
##   Fixed: TOTALS ~ MAD 
## (Intercept)       MADMM        MADM       MADSM 
##   157.67628    50.31245    69.59725    66.63503 
## 
## Random effects:
##  Formula: ~1 | REP
##         (Intercept) Residual
## StdDev:   0.1187511  15.3783
## 
## Number of Observations: 24
## Number of Groups: 3</code></pre>
<p><img src="madAcids_files/figure-html/unnamed-chunk-32-1.png" width="960" style="display: block; margin: auto;" /><img src="madAcids_files/figure-html/unnamed-chunk-32-2.png" width="960" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.95588, p-value = 0.3613</code></pre>
</div>
<div id="anova-5" class="section level4">
<h4>Anova</h4>
<pre><code>##             numDF denDF  F-value p-value
## (Intercept)     1    18 4234.257  &lt;.0001
## MAD             3    18   26.349  &lt;.0001</code></pre>
</div>
<div id="test-de-tukey-5" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## $emmeans
##  MAD emmean   SE df lower.CL upper.CL
##  I      158 6.28  2      131      185
##  MM     208 6.28  2      181      235
##  M      227 6.28  2      200      254
##  SM     224 6.28  2      197      251
## 
## Degrees-of-freedom method: containment 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast estimate   SE df t.ratio p.value
##  I - MM     -50.31 8.88 18  -5.667  0.0001
##  I - M      -69.60 8.88 18  -7.839  &lt;.0001
##  I - SM     -66.64 8.88 18  -7.505  &lt;.0001
##  MM - M     -19.28 8.88 18  -2.172  0.1689
##  MM - SM    -16.32 8.88 18  -1.838  0.2886
##  M - SM       2.96 8.88 18   0.334  0.9868
## 
## Degrees-of-freedom method: containment 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="madAcids_files/figure-html/unnamed-chunk-34-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="conclusiones-5" class="section level4">
<h4>Conclusiones</h4>
<p>La menor concentración de ácidos totales en frutos inmaduros es
significativa.</p>
</div>
</div>
<div id="ácido-tartárico-1" class="section level3">
<h3>Ácido tartárico</h3>
<div id="modelo-y-supuestos-5" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Error in matrix(unlist(value), nrow = nrow(data), dimnames = list(row.names(data), : length of &#39;dimnames&#39; [2] not equal to array extent</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2s&#39; not found</code></pre>
<pre><code>## Error: object &#39;tars_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;tars_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;HVtars&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;tars_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;QQtars&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2s&#39; not found</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.95588, p-value = 0.3613</code></pre>
</div>
<div id="anova-6" class="section level4">
<h4>Anova</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2s&#39; not found</code></pre>
</div>
<div id="test-de-tukey-6" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mtar2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Comptars&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Comptars&#39; not found</code></pre>
</div>
<div id="conclusiones-6" class="section level4">
<h4>Conclusiones</h4>
<p>Existen diferencias significativas entre estados de Maturity. Sólo el
estado sobre maduro presentó ácido málico detectable.</p>
</div>
</div>
<div id="ácido-málico-1" class="section level3">
<h3>Ácido málico</h3>
<div id="modelo-y-supuestos-6" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Error in matrix(unlist(value), nrow = nrow(data), dimnames = list(row.names(data), : length of &#39;dimnames&#39; [2] not equal to array extent</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2s&#39; not found</code></pre>
<pre><code>## Error: object &#39;mals_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mals_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;HVmals&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mals_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;QQmals&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2s&#39; not found</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.95588, p-value = 0.3613</code></pre>
</div>
<div id="anova-7" class="section level4">
<h4>Anova</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2s&#39; not found</code></pre>
</div>
<div id="test-de-tukey-7" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mmal2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compmals&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compmals&#39; not found</code></pre>
</div>
<div id="conclusiones-7" class="section level4">
<h4>Conclusiones</h4>
<p>Existen diferencias significativas entre estados de Maturity. En el
estado maduro se presentó el pico de concentración de ácido málico.</p>
</div>
</div>
<div id="ácido-quínico-1" class="section level3">
<h3>Ácido quínico</h3>
<div id="modelo-y-supuestos-7" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Error in matrix(unlist(value), nrow = nrow(data), dimnames = list(row.names(data), : length of &#39;dimnames&#39; [2] not equal to array extent</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2s&#39; not found</code></pre>
<pre><code>## Error: object &#39;quis_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;quis_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;HVquis&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;quis_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;QQquis&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2s&#39; not found</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.95588, p-value = 0.3613</code></pre>
</div>
<div id="anova-8" class="section level4">
<h4>Anova</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2s&#39; not found</code></pre>
</div>
<div id="test-de-tukey-8" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;mqui2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compquis&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compquis&#39; not found</code></pre>
</div>
<div id="conclusiones-8" class="section level4">
<h4>Conclusiones</h4>
<p>El estado inmaduro se diferenció significativamente por sus bajas
concentraciones de quínico. Luego durante la maduración el ácido se
mantiene constante.</p>
</div>
</div>
<div id="ácido-succinico-1" class="section level3">
<h3>Ácido succinico</h3>
<div id="modelo-y-supuestos-8" class="section level4">
<h4>Modelo y supuestos</h4>
<pre><code>## Error in matrix(unlist(value), nrow = nrow(data), dimnames = list(row.names(data), : length of &#39;dimnames&#39; [2] not equal to array extent</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2s&#39; not found</code></pre>
<pre><code>## Error: object &#39;sucs_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;sucs_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;HVsucs&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;sucs_ajuste&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;QQsucs&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2s&#39; not found</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.95588, p-value = 0.3613</code></pre>
<pre><code>## Error in `contrasts&lt;-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]): contrasts can be applied only to factors with 2 or more levels</code></pre>
</div>
<div id="anova-9" class="section level4">
<h4>Anova</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2s&#39; not found</code></pre>
</div>
<div id="test-de-tukey-9" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;msuc2s&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compsucs&#39; not found</code></pre>
<pre><code>## Error in eval(expr, envir, enclos): object &#39;Compsucs&#39; not found</code></pre>
</div>
<div id="conclusiones-9" class="section level4">
<h4>Conclusiones</h4>
<p>Se encontraron diferencias significativas entre estados de Maturity,
los frutos inmaduros y sobre maduros presentaron las mayores
concentraciones de ácido succínico.</p>
</div>
</div>
</div>
<div id="correlaciones-ácidos-orgánicos-y-acidez-total-titulable-att."
class="section level2">
<h2>Correlaciones ácidos orgánicos y acidez total titulable ATT.</h2>
<div id="tabla-de-ácidos" class="section level3">
<h3>Tabla de ácidos</h3>
<pre><code>##      CAR MAD  N       CONS          sd         se          ci
## 1    ATT   I  3   1.779200  0.05079843 0.02932848  0.12619028
## 2    ATT  MM  3   1.606400  0.02789695 0.01610631  0.06929987
## 3    ATT   M  3   1.828267  0.20390638 0.11772541  0.50653154
## 4    ATT  SM  3   1.384533  0.08352756 0.04822466  0.20749396
## 5   &lt;NA&gt;   I 24  39.419071 47.80778177 9.75872259 20.18745575
## 6   &lt;NA&gt;  MM 24  51.997183 41.36096715 8.44277206 17.46520468
## 7   &lt;NA&gt;   M 24  56.818384 47.30540308 9.65617497 19.97531984
## 8   &lt;NA&gt;  SM 24  56.077828 47.57987226 9.71220076 20.09121801
## 9  ACIDS   I  6 157.676284 24.41479565 9.96729859 25.62175670
## 10 ACIDS  MM  6 207.988730 11.65695733 4.75893290 12.23322648
## 11 ACIDS   M  6 227.273538  4.28462561 1.74919108  4.49643882
## 12 ACIDS  SM  6 224.311311 13.98740581 5.71033451 14.67888217</code></pre>
</div>
</div>
<div
id="concentración-del-ratio-azúcares-totales-ácidos-orgánicos-totales-a-distintos-estados-de-madurez."
class="section level2">
<h2>Concentración del ratio azúcares totales / ácidos orgánicos totales
a distintos estados de Madurez.</h2>
<p><img src="madAcids_files/figure-html/unnamed-chunk-52-1.png" width="960" style="display: block; margin: auto;" /></p>
<div id="tabla-descriptiva-totales-2" class="section level4">
<h4>Tabla descriptiva totales</h4>
<pre><code>##   MAD N   TOTALS          sd          se         ci
## 1   I 3 1.721122 0.263331773 0.152034670 0.65415239
## 2  MM 3 1.447652 0.116290919 0.067140593 0.28888266
## 3   M 3 1.541716 0.132691300 0.076609358 0.32962346
## 4  SM 3 1.909504 0.007733369 0.004464862 0.01921075</code></pre>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: dataSTAT 
##   Log-restricted-likelihood: 1.185396
##   Fixed: TOTALS ~ MAD 
## (Intercept)       MADMM        MADM       MADSM 
##   1.7211225  -0.2734708  -0.1794066   0.1883818 
## 
## Random effects:
##  Formula: ~1 | REP
##          (Intercept) Residual
## StdDev: 0.0009997037 0.158534
## 
## Number of Observations: 12
## Number of Groups: 3</code></pre>
<p><img src="madAcids_files/figure-html/unnamed-chunk-54-1.png" width="960" style="display: block; margin: auto;" /><img src="madAcids_files/figure-html/unnamed-chunk-54-2.png" width="960" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  e
## W = 0.92623, p-value = 0.3418</code></pre>
</div>
<div id="anova-10" class="section level4">
<h4>Anova</h4>
<pre><code>##             numDF denDF   F-value p-value
## (Intercept)     1     6 1307.5624  &lt;.0001
## MAD             3     6    4.9724  0.0457</code></pre>
</div>
<div id="test-de-tukey-10" class="section level4">
<h4>Test de Tukey</h4>
<pre><code>## $emmeans
##  MAD emmean     SE df lower.CL upper.CL
##  I     1.72 0.0915  2     1.33     2.11
##  MM    1.45 0.0915  2     1.05     1.84
##  M     1.54 0.0915  2     1.15     1.94
##  SM    1.91 0.0915  2     1.52     2.30
## 
## Degrees-of-freedom method: containment 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast estimate    SE df t.ratio p.value
##  I - MM     0.2735 0.129  6   2.113  0.2498
##  I - M      0.1794 0.129  6   1.386  0.5497
##  I - SM    -0.1884 0.129  6  -1.455  0.5142
##  MM - M    -0.0941 0.129  6  -0.727  0.8831
##  MM - SM   -0.4619 0.129  6  -3.568  0.0443
##  M - SM    -0.3678 0.129  6  -2.841  0.1041
## 
## Degrees-of-freedom method: containment 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p><img src="madAcids_files/figure-html/unnamed-chunk-56-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="conclusiones-10" class="section level4">
<h4>Conclusiones</h4>
<p>Existen diferencias significativas entre estados de Maturity para la
relación azúcares totales / ácidos totales. La diferencia está dada
únicamente entre los niveles MM y SM.</p>
</div>
</div>
<div id="correlaciones" class="section level2">
<h2>Correlaciones</h2>
<div id="correlaciones-de-pearson." class="section level3">
<h3>Correlaciones de Pearson.</h3>
<p><img src="madAcids_files/figure-html/unnamed-chunk-58-1.png" width="1152" style="display: block; margin: auto;" /></p>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  FACO$Málico and FACO$Quínico
## t = 5.3299, df = 10, p-value = 0.000333
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.5649710 0.9600656
## sample estimates:
##       cor 
## 0.8600213</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  FACO$Tartárico and FACO$Succínico
## t = 2.9895, df = 10, p-value = 0.01358
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1866812 0.9043389
## sample estimates:
##       cor 
## 0.6869819</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  FACO$ATT and FACO$Tartárico
## t = -3.2686, df = 10, p-value = 0.00845
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.9151410 -0.2464551
## sample estimates:
##        cor 
## -0.7187027</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  FACO$ACIDS and FACO$Quínico
## t = 5.2307, df = 10, p-value = 0.0003839
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.5539018 0.9587847
## sample estimates:
##       cor 
## 0.8557676</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  FACO$ACIDS and FACO$Málico
## t = 8.0069, df = 10, p-value = 1.169e-05
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7639902 0.9805782
## sample estimates:
##       cor 
## 0.9300893</code></pre>
</div>
<div id="gráficos-de-correlación-detallados-por-estados-de-madurez"
class="section level3">
<h3>Gráficos de correlación detallados por estados de madurez</h3>
<p><img src="madAcids_files/figure-html/unnamed-chunk-60-1.png" width="1152" style="display: block; margin: auto;" /></p>
<div id="conclusión" class="section level4">
<h4>Conclusión</h4>
<p>Linear relationships between organic acids became evident between
Malic and Quinic acid with an r=0.8600213 and a p-value=0.000333, and
between Tartaric and Succinic acid with an r=0.6869819 and a
p-value=0.01358. Total titratable acidity (TTA) showed a significant
linear association only with Tartaric acid with an r=-0.7187027 and a
p-value=0.00845. However, this inverse association is linked to the fact
that Tartaric acid only appears in trace amounts in overripe fruits.
Total acids with Quinic acid presented a correlation of 0.8557676 with a
p-value=0.0003839. Meanwhile, Malic acid an r=0.9300893 and a
p-value=1.169e-05. In both cases, these acids explain the increase in
total acid concentration throughout fruit ripening.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
