---
title: "Fenoles"
output:
 html_document:
   toc: true
   toc_depth: 5
   toc_float:
     collapsed: false
     smooth_scroll: true
---

Análisis sobre la concentración de fenoles expresados en mg equivalente de ácido tánico cada 100g PF
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(readxl)
data_mad_phenols <- read_excel("database.xlsx", sheet = "mad_phenols")
data_mad_phenols$madurez <- factor(data_mad_phenols$madurez, levels=c("I", "MM", "M", "SM"))

```

Tabla descriptiva
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(dplyr)
tabla_fenoles <- data_mad_phenols %>% 
  dplyr::group_by(madurez) %>% 
  dplyr::summarise(n=n(),
                   Mean = mean(fenoles),
                   sd = sd(fenoles))

library(knitr)
kable(tabla_fenoles, format = "markdown")

```

Gráfico de puntos
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)
plot_mad_fenoles <- ggplot(tabla_fenoles, aes(x = madurez, y = Mean, color = madurez)) +
    scale_color_manual(values = c("palegreen4", "yellowgreen", "gold", "gold4")) +
    stat_summary(fun = "mean", size = 6, geom = "point") +
    geom_errorbar(aes(ymin = Mean - sd, ymax = Mean + sd), width = 0.2, position = position_dodge(0.9)) +
    theme_classic() +
    theme(legend.title = element_blank()) +
    theme(legend.position = "none") +
    theme(text = element_text(size = 15, color = 'black')) +
    theme(axis.text = element_text(color = 'black'))
plot_mad_fenoles

```

Modelo
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(nlme)
modelos_mad_fenoles <- gls(fenoles ~ madurez, weights=varIdent(form=~1|madurez), data=data_mad_phenols)
modelos_mad_fenoles

```

Supuestos
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

fenoles_mad_ajuste <- as.data.frame(cbind(
  "residuos" = residuals(modelos_mad_fenoles),
  "predichos" = predict(modelos_mad_fenoles)))

HV_fenoles_mad<-ggplot(fenoles_mad_ajuste) +
  aes(predichos, residuos) +
  geom_hline(yintercept = 0, colour="white", size=2) +
  geom_point(colour="white")+
  theme_classic()+
  labs(y="Residuals", x="Predicted values")+
  theme(legend.position = "bottom", legend.background = element_rect(fill = "gray12"))+
  theme(panel.grid.major.y = element_line(size=0.05, color='white'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='white'))+
  theme(axis.text = element_text(color='white'))+
  theme(plot.background = element_rect(fill = "gray12"))+
  theme(panel.background = element_rect(fill = "gray12", color = "white"))
HV_fenoles_mad

QQ_fenoles_mad<-ggplot(fenoles_mad_ajuste) +
aes(sample = residuos) +
  geom_qq(shape = 1, colour="white") +
  geom_qq_line(colour="white")+
  theme_classic()+
  labs(y="Sample Quantiles", x="Theoretical Quantiles")+
  theme(legend.position = "bottom", legend.background = element_rect(fill = "gray12"))+
  theme(panel.grid.major.y = element_line(size=0.05, color='white'))+
  theme(panel.grid.major.x = element_blank())+
  theme(text = element_text(size=10, color='white'))+
  theme(axis.text = element_text(color='white'))+
  theme(plot.background = element_rect(fill = "gray12"))+
  theme(panel.background = element_rect(fill = "gray12", color = "white"))
QQ_fenoles_mad

shapiro.test(fenoles_mad_ajuste$residuos)

```

Anova
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

anova(modelos_mad_fenoles)

```

Test de Tukey
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(emmeans)
Comp_mad_fenoles<-emmeans(modelos_mad_fenoles, pairwise ~ madurez) #Tukey por default  
Comp_mad_fenoles
plot(Comp_mad_fenoles, comparisons = FALSE, arrow.type = "none") + theme_classic() +
  labs(x = "mg Fenoles / 100g PF)", y ="Madurez")

```

Correlación Fenoles - DPPH

```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(readxl)
library(dplyr)

Datos0 <- read_excel("database.xlsx", sheet = "mad_aaox")
Datos0$Muestra <- factor(Datos0$Muestra)
Datos0$Conc <- factor(Datos0$Conc)
Datos0$Pip <- factor(Datos0$Pip)
Datos0$Trata <- factor(Datos0$Trata, levels = c("I", "MM", "M", "SM"))

# Datos0 %>% dplyr::filter(Conc == extract_Conc)

filter_list <- c("1.25", "2.5", "5", "12.5")
names_Conc<- c("ext_1.25", "ext_2.5", "ext_5", "ext_12.5")
list_Conc <- list()
for (extract_Conc in filter_list) {
  temp_table <- Datos0 %>% filter(Conc == extract_Conc)

  # Cambia el nombre de la columna Conc
  colnames(temp_table)[which(colnames(temp_table) == "In")] <- names_Conc
  # Selecciona las columnas 1 y 4
  temp_table <- temp_table %>% select(1, 4)
  # Agrega la tabla a la lista
  list_Conc[[paste0("extract_", extract_Conc)]] <- temp_table
  
}
# Une las tablas por columna
all_conc <- bind_cols(list_Conc)
# Elimina las columnas duplicadas
all_conc <- all_conc[,-c(3,5,7)]
# Se agrega columna de fenoles
all_conc <-cbind(all_conc, data_mad_phenols[,-c(1)]) 

```

```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=16, fig.height=14}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)
library(GGally)
GCORmad <- ggpairs(all_conc, columns = 2:9, lower = list(continuous = "points"))
GCORmad + theme_minimal()

```

Valores p para H0: beta1=beta0
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

# new names
all_conc <- rename(all_conc, ext_1.25=ext_1.25...2)
all_conc <- rename(all_conc, ext_2.5=ext_1.25...4)
all_conc <- rename(all_conc, ext_5=ext_1.25...6)
all_conc <- rename(all_conc, ext_12.5=ext_1.25...8)

# models
mod_1.25<- lm(ext_1.25~fenoles, data=all_conc)
mod_2.5<- lm(ext_2.5~fenoles, data=all_conc)
mod_5<- lm(ext_5~fenoles, data=all_conc)
mod_12.5<- lm(ext_12.5~fenoles, data=all_conc)

```

Concentración 1,25
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(knitr)
kable(summary(mod_1.25)$coefficients[2,4], format = "markdown", col.names = "p-valor")

```
Concentración 2,5
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

kable(summary(mod_2.5)$coefficients[2,4], format = "markdown", col.names = "p-valor")

```
Concentración 5
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

kable(summary(mod_5)$coefficients[2,4], format = "markdown", col.names = "p-valor")

```
Concentración 12,5
```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

kable(summary(mod_12.5)$coefficients[2,4], format = "markdown", col.names = "p-valor")

```