---
title: "Maturity"
output:
 html_document:
   toc: true
   toc_depth: 5
   toc_float:
     collapsed: false
     smooth_scroll: true
---



## Tablas resumen

### Acidos
```{r,fig.align='center',echo=FALSE, error=TRUE}
#setwd("C:/Users/um/Documents/ipovilonis/Doc/6 - Producción/web/ipovilonis.github.io")
library(png)
library(grid)
img <- readPNG("acidos.png")
grid.raster(img)
```

### Carbohydrates
```{r,fig.align='center',echo=FALSE, error=TRUE}
#setwd("C:/Users/um/Documents/ipovilonis/Doc/6 - Producción/web/ipovilonis.github.io")
library(png)
library(grid)
img <- readPNG("azucares.png")
grid.raster(img)
```

### Dietary fibers

```{r,fig.align='center',echo=FALSE, error=TRUE}

library(png)
library(grid)
img <- readPNG("fibras.png")
grid.raster(img)
```

### Cations
```{r,fig.align='center',echo=FALSE, error=TRUE}
#setwd("C:/Users/um/Documents/ipovilonis/Doc/6 - Producción/web/ipovilonis.github.io")
library(png)
library(grid)
img <- readPNG("cationes.png")
grid.raster(img)
```

Nota: *Se ajustaron modelos lineales mixtos (estimaciones por máxima verosimilitud restringida REML) para predecir las concentraciones (CON) de ácidos y sacáridos en función del estado de madurez (MAD). Las repeticiones (REP) fueron incluidas como efectos aleatorios.*

```{r, echo=FALSE, error=TRUE, fig.align='center', fig.asp=0.4, fig.width=10, fig.height=8}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(lattice)
library(Rmisc)
estmal <- summarySE(mal, measurevar="CONS", groupvars=c("MAD"))
estqui <- summarySE(qui, measurevar="CONS", groupvars=c("MAD"))
estsuc <- summarySE(suc, measurevar="CONS", groupvars=c("MAD"))
estsac <- summarySE(sac, measurevar="CONS", groupvars=c("MAD"))
estglu <- summarySE(glu, measurevar="CONS", groupvars=c("MAD"))
estfru <- summarySE(fru, measurevar="CONS", groupvars=c("MAD"))
estmg <- summarySE(mg, measurevar="CONS", groupvars=c("MAD"))
estk <- summarySE(k, measurevar="CONS", groupvars=c("MAD"))
estmn <- summarySE(mn, measurevar="CONS", groupvars=c("MAD"))
```
