---
title: "Modelos y Supuestos"
output: word_document
---
### El modelo de distribución normal se expresa como:

$$
E[Y_{ijkl}] = \mu + \alpha_i + \beta_j + (\gamma_k(\beta_j)) + \epsilon_{ijkl}
$$

- \(E[Y_{ijkl}]\) es la esperanza de la respuesta.
- \(\mu\) es la media general.
- \(\alpha_i\) es el efecto del nivel \(i\) del factor `year`.
- \(\beta_j\) es el efecto del nivel \(j\) del factor `site`.
- \(\gamma_k(\beta_j)\) es el efecto del nivel \(k\) del factor anidado `phenotype` dentro de `site`.
- \(\epsilon_{ijkl}\) son los errores aleatorios.

### Supuestos del Modelo Normal

1. **Distribución de la Variable Respuesta:**

   La variable de respuesta sigue una distribución normal:

   $$
   Y_{ijkl} \sim \mathcal{N}(\mu, \sigma^2)
   $$

2. **Independencia de los Errores:**

   Los errores son independientes y siguen una distribución normal:

   $$
   \epsilon_{ijkl} \sim \mathcal{N}(0, \sigma^2)
   $$

3. **Homocedasticidad:**

   La varianza es constante para todos los niveles de los factores:

   $$
   \text{Var}(\epsilon_{ijkl}) = \sigma^2
   $$

---

### Modelo Poisson con Anidación

```markdown
### El modelo de distribución Poisson se expresa como:

$$
E[Y_{ijkl}] = \exp(\mu + \alpha_i + \beta_j + (\gamma_k(\beta_j)))
$$

- \(E[Y_{ijkl}]\) es la esperanza de la respuesta.
- \(\mu\) es la media general.
- \(\alpha_i\) es el efecto del nivel \(i\) del factor `year`.
- \(\beta_j\) es el efecto del nivel \(j\) del factor `site`.
- \(\gamma_k(\beta_j)\) es el efecto del nivel \(k\) del factor anidado `phenotype` dentro de `site`.

### Supuestos del Modelo Poisson

1. **Distribución de la Variable Respuesta:**

   La variable de respuesta sigue una distribución Poisson:

   $$
   Y_{ijkl} \sim \text{Poisson}(\lambda_{ijkl})
   $$

2. **Función de Enlace:**

   La relación entre los predictores y la media de la distribución Poisson está dada por la función de enlace logarítmica:

   $$
   \log(\lambda_{ijkl}) = \mu + \alpha_i + \beta_j + (\gamma_k(\beta_j))
   $$

3. **Independencia de las Observaciones:**

   Las observaciones son independientes:

   $$
   \epsilon_{ijkl} \sim \text{Independiente}
   $$

4. **Varianza de la Distribución Poisson:**

   La varianza de la respuesta Poisson es igual a su media:

   $$
   \text{Var}(Y_{ijkl}) = \lambda_{ijkl}
   $$

### Código para Modelos en R

```r
# Modelo Normal con anidación de phenotype en site
rpt_normal <- rptGaussian(y ~ (1|year) + (1|site) + (1|site:phenotype),
                          grname=c("year", "site", "phenotype", "Residual"),
                          data=datosff, nboot=3, npermut=3)

# Modelo Poisson con anidación de phenotype en site
rpt_poisson <- rptPoisson(y ~ (1|year) + (1|site) + (1|site:phenotype),
                          grname=c("year", "site", "phenotype", "Residual"),
                          data=datosff, link="log", nboot=3, npermut=3)
