---
title: "Phenotypes"
output: html_document
runtime: shiny
---

```{r, echo=FALSE, fig.align='center', fig.asp=0.4}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)

library(ggplot2)

dataCAR<-read.delim("CAR.txt")
dataCAR$phenotype<-as.factor(dataCAR$phenotype)
dataCAR$site<-factor(dataCAR$site,levels=c("Concordia", "Palmar", "Gualeguaychu"))

datashow<-dataCAR[,-c(1,2)]

```

## Cast

```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("variable", label = "Variable: ",
              choices = colnames(datashow), selected = "dbh")
)

renderPlot({
  plot0<-ggplot(dataCAR, aes_string(x=dataCAR$phenotype, y=input$variable, color=dataCAR$site))+
    geom_point(size=5)+
    theme_classic()+
    scale_color_manual(values=c("coral1","burlywood2","palegreen4"))+
    theme(plot.margin = margin(0.25, 0.5, 0.25, 0.5, "cm"), #ajustar los margenes del gráfico
        panel.background = element_rect(fill = "gray100", colour = "gray100", size = 2, linetype = "solid"), #fondo del gráfico
        panel.grid.major = element_line(size = 0.25, linetype = 'solid', colour = "gray80"), #lineas del gráfico
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "gray90"), #líneas auxiliares
        title=element_text(size=25, face = "bold"), #tamaño de titulo del mapa
        legend.key.size = unit(0.4, "cm"), #alto de cuadrados de referencia
        legend.key.width = unit(0.5,"cm"), #ancho de cuadrados de referencia 
        legend.position="top", #ubicacion de leyenda
        legend.direction = "horizontal", #dirección de la leyenda
        legend.title=element_text(size=10, face = "bold"), #tamaño de titulo de leyenda
        legend.text=element_text(size=8), #tamaño de texto de leyenda
        plot.caption=element_text("none"), #tamaño de nota al pie: face = "italic", colour = "gray35",size=6
        axis.title = element_text("none"),
        panel.grid.major.x = element_blank(),#tamaño y color de referencias de ejes X e Y
        axis.text.x = element_text(colour = "black",size = 20, angle = 90), #tamaño y color del texto de eje X
        axis.text.y = element_text(colour = "black",size = 20)) #tamaño y color del texto de eje Y
  plot0
    

})
```


```{r, echo=FALSE}
# 
#   dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  # lines(dens, col = "blue")


# library(shiny)
# 
# shinyApp(
#   fluidPage(
#     titlePanel("Phenotypes"),
#     sidebarLayout(
#       selectInput(inputId = "accesion",
#           "Select Phenotype:",
#           choices = c("dbh", "height"),
#           selected = height,
#       mainPanel()
#       )
# 
#     )
# 
#   ),
# 
#   function(input, output) {
#    output$select <- renderPlot({
#   hist(input$accesion, probability = TRUE, breaks = as.numeric(10),
#        xlab = "", main = "")
# 
# })
#   }
# )

```