---
title: "Publicaciones"
---

* [*Hexachlamys edulis* (Berg) Kausel & Legrand, “ubajay”, a native fruit species from South America](https://oaj.fupress.net/index.php/ahs/article/view/10660)

* [Changes in physicochemical properties at different development stages of *Hexachlamys edulis* fruit, an underutilized South American species](https://doi.org/10.1016/j.heliyon.2021.e08323)

* [“Changes in carbohydrates, organic acids and minerals at different development stages of Hexachlamys edulis fruit, a promising option from South America.”](https://www.mdpi.com/2311-7524/9/3/314/htm)

* [“Flower and fruit formation of Hexachlamys edulis in Buenos Aires, Argentina.”](https://www.jaeid.it/index.php/jaeid/article/view/13261/11905)

#### Próximamente

* [“Analysis of Associated Woody and Semi-woody Local Wild Species in Entre Ríos, Argentina: Exploring the Agricultural Potential of Hexachlamys edulis.”](https://www.preprints.org/manuscript/202409.0304/v1)

# Presentaciones en eventos científicos

* [“Caracterización Físico-Química de diversos frutos subutilizados de Argentina para su valoración como alimentos funcionales”. Investigación, Ciencia y Universidad. ISSN 2525-1783. S.l., v. 3, n. 4, p. 51 · 1 feb. 2020](http://repositorio.umaza.edu.ar//handle/00261/1634)

* [“Especies vegetales asociadas al Ubajay (Hexachlamys edulis) en la costa oriental de Entre Ríos”. Revista 2020 de las XXXIV Jornadas Forestales de Entre Ríos. · 1 oct. 2020](https://www.jornadasforestales.com.ar/book/2020.html)

* [“EL UBAJAY (Hexachlamys edulis) UNA ESPECIE NATIVA COMO PRODUCTO FORESTAL NO MADERABLE". Revista 2020 de las XXXIV Jornadas Forestales de Entre Ríos”. · 1 oct. 2020](https://www.jornadasforestales.com.ar/book/2020.html)

* [“Avances de estudios interdisciplinarios en Hexachlamys edulis (O. Berg) Kausel & D. Legrand, "ubajay", una especie frutal nativa de Argentina con potencial productivo e interés como alimento funcional” III Simposio de Investigadores UM · 4 nov. 2020](https://repositorio.unimoron.edu.ar/handle/10.34073/266)

* [Hexachlamys edulis "ubajay", una especie subutilizada. I. Cambios en las propiedades fisicoquímicas durante la maduración de los frutos. III CONGRESO ARGENTINO DE BIOLOGÍA Y TECNOLOGÍA POSTCOSECHA · 26 jul. 2021](https://www.fiq.unl.edu.ar/institucional/wp-content/uploads/sites/3/2021/08/Libro-de-Res%C3%BAmenes-III-CABTP-con-ISBN.pdf)

* [Hexachlamys edulis "ubajay", una especie subutilizada. II. Cambios en las clorofilas, carotenoides y biofenoles durante la maduración de los frutos. III CONGRESO ARGENTINO DE BIOLOGÍA Y TECNOLOGÍA POSTCOSECHA · 26 jul. 2021](https://www.fiq.unl.edu.ar/institucional/wp-content/uploads/sites/3/2021/08/Libro-de-Res%C3%BAmenes-III-CABTP-con-ISBN.pdf)

* [Estudio de la Morfología de Frutos para la Valoración de Hexachlamys edulis 3ras Jornadas de Investigación de Agronomía, Agroindustrias, Enología y Alimentos · 19 ago. 2021](http://www.crup.org.ar/document/download/807/)

* [Estudio de Características Florales para la Valoración de Hexachlamys edulis 3ras Jornadas de Investigación de Agronomía, Agroindustrias, Enología y Alimentos · 19 ago. 2021](http://www.crup.org.ar/document/download/807/)

* [Caracterización de la variabilidad fenotípica de los frutos de ubajay (Hexachlamys edulis). 41° Congreso Argentino de Horticultura · 4 oct. 2021](https://www.youtube.com/watch?v=LVt4-fyNiWQ&list=PLVw1YTJX8OrQOUuVMSDOq5UMaETwcLmt-&t=10s)

* [Fenología del ubajay (Hexachlamys edulis) en relación a las condiciones climáticas de Moreno (Pcia de Buenos Aires). 41° Congreso Argentino de Horticultura · 4 oct. 2021](https://www.youtube.com/watch?list=PLVw1YTJX8OrTw3WvMKEcICSj14suTqibz&v=9PmGkG4dA0A)

* [“Efecto de la temperatura de conservación sobre propiedades químicas de los frutos de Hexachlamys edulis en Concordia, Entre Ríos.” VIII Congreso Internacional de Ciencia y Tecnología de Alimentos (CICYTAC) · 4 oct. 2022](https://cicytac.cba.gov.ar/)

* [“Efecto de la temperatura de conservación sobre las propiedades físicas de los frutos de Hexachlamys edulis en Concordia, Entre Ríos.” VIII Congreso Internacional de Ciencia y Tecnología de Alimentos (CICYTAC) · 4 oct. 2022](https://cicytac.cba.gov.ar/)

* [Prospección y mejoramiento de frutales exóticos y nativos de importancia para el norte argentino: "Avances en estudios sobre la variabilidad fenotípica de Hexachlamys edulis". L Congreso Argentino de Genética · 5 oct. 2022](https://sag.org.ar/congreso2022/simposios/)

* [IX Jornadas de Ciencia y Tecnología UM. “Estado de avance en la prospección y mejoramiento del ubajay (Hexachlamys edulis) en el litoral argentino.” 29 may. 2023](https://www.unimoron.edu.ar/static/media/doc_7ca663be2bdb11ee8ef50242ac170005_o.pdf)

* [IV Congreso Argentino de Biología y Tecnología Postcosecha. “UBAJAY (Hexachlamys edulis O. BERG, KAUSEL & LEGRAND) ¿Una especie silvestre de frutos con comportamiento climatérico?” 31 ago. 2023](https://revistas.unlp.edu.ar/InvJov/article/view/16147/15415)

* [4tas. Jornadas de Investigación en Agronomía, Agroindustrias, Enología y Alimentos del CRUP· "Estudios multidisciplinarios en frutales nativos y especies subutilizadas en Argentina para su aprovechamiento sustentable." 2 oct. 2023](https://umazaeduar-my.sharepoint.com/personal/cromero_umaza_edu_ar/_layouts/15/stream.aspx?id=%2Fpersonal%2Fcromero%5Fumaza%5Fedu%5Far%2FDocuments%2FDatos%20adjuntos%2FEspecies%20nativas%20de%20frutales%20desde%20el%20recurso%20gen%C3%A9tico%20a%20la%20cadena%20de%20producci%C3%B3n%5FParte%202%2Emp4&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E5c49489b%2D5b25%2D4291%2Da452%2De75564cd33b0)

* [Jornadas del CUIA en Argentina. Consorzio interuniversitario Italiano per l’ Argentina. WORKSHOP: Especies nativas, producción agrícola y crianza: "Frutas nativas argentinas: distintos estados de valorización y uso". 13 may. 2024](https://www.cuia.net/wp-content/uploads/2024/04/CUIA-2024-Aggiornato.pdf)

* [Expo Doctorado. Escuela para Graduados Ing. Agr. Alberto Soriano - FAUBA. "Desde la floración a la postcosecha: fisiología, morfología y bioquímica de un frutal subutilizado de Argentina, el “ubajay” (Hexachlamys edulis (O. Berg) Kausel & D. Legrand)." 5 sep. 2024](https://www.youtube.com/watch?v=NEKUe7lck0A&t=1660s)

* [ASAHO. "Cuantificación de atributos de calidad y análisis de la variabilidad fenotípica en frutos
de ubajay (Hexachlamys edulis)." 4 sep. 2024
](https://asaho.org/libro-de-resumenes-42-congreso-argentino-de-horticultura/)

### Próximamente

* [VI Simposio de Investigadores de la UM. "Incorporación de Ubajay (Hexachlamys edulis O. Berg Kausel & D. Legrand) y Calafate (B. microphylla (ex B. buxifolia)) en barras de cereal.". 8 oct. 2024](http://secyt.unimoron.edu.ar/)

* [VI Simposio de Investigadores de la UM. "Avances en la prospección, caracterización y valoración del Ubajay (Hexachlamys edulis (H. edulis) O. Berg Kausel & D. Legrand)". 8 oct. 2024](http://secyt.unimoron.edu.ar/)

* [CASLAN. "Nuevos sabores del bosque: Ubajay y Calafate, incorporación de compuestos nutracéuticos en snacks." 14 nov. 2024](https://caslan2024.unimoron.edu.ar/)

